### ISSUE TITLE
Tags h1 in article_html - indented behavior?

### ISSUE THREAD

**Issue by ecesena** [codelucas/newspaper#107]
Hi, while extracting `article_html`, I noticed that sometimes the title is present as `<h1>` in the result, while most of the times it seems that it gets removed.

I'm wondering what is the intended behavior. For instance, the readability service provides the content *without* the title as `<h1>` tag.

Examples with title as `<h1>` in `article_html`:
http://patch.com/virginia/leesburg/third-four-classical-concerts-old-stone-school-finishes-standing-ovation-and-encore-performance
http://blogs.nordstrom.com/fashion/whats-cooking-holiday-entertaining-menu-1st-course-bistro-crab-stack-salad/
http://www.people.com/article/dustin-lynch-injured-flying-beer-can-concert-florida-mulletfest
http://www.npr.org/blogs/thetwo-way/2014/10/31/360358304/no-joke-french-town-cracks-down-on-clown-costumes-after-attacks

**Comment by codelucas** [comment]
Refer to this: https://github.com/codelucas/newspaper/pull/106

It has not been pushed yet .. But look at what it does and see how it will affect this issue.

**Comment by ecesena** [comment]
Hi, I was more worried because sometimes `<h1>` is included, other times it isn't, and I was wondering what should we expect. Thanks for the answer, I'm closing this ticket and will refer to the other one.
