### ISSUE TITLE
newspaper.build( ) error

### ISSUE THREAD

**Issue by adeze** [codelucas/newspaper#111]
Hi, when i try to test with the quick start example 

```
>>> import newspaper

>>> cnn_paper = newspaper.build('http://cnn.com')

>>> for article in cnn_paper.articles:
>>>     print(article.url)
```

i get an error

```
Traceback (most recent call last):

  File "<ipython-input-23-f22cd7df4cac>", line 3, in <module>
    cnn_paper = newspaper.build('http://cnn.com')

  File "/Users/Adam/anaconda/lib/python3.4/site-packages/newspaper/api.py", line 31, in build
    s.build()

  File "/Users/Adam/anaconda/lib/python3.4/site-packages/newspaper/source.py", line 92, in build
    self.download(response)

TypeError: download() takes 1 positional argument but 2 were given

```

i'm using spyder(python 3.4) through anaconda if that makes a different, but getting an article directly works OK. I'm fairly new to python, so is there something i'm missing? 
thanks

**Comment by codelucas** [comment]
Fixed in https://github.com/codelucas/newspaper/commit/95f66da2e0e1b4ade435ac3a940dd3541eb7383d,
great catch, it's been pushed live onto pypi.

**Comment by codelucas** [comment]
Explanation of why such a dumb bug got pushed:
I was trying to mock HTML downloads for source objects but it wasn't as easy as I'd hoped for a variety of reasons, so I had commented out the unit tests for `source.py` without removing changes that I had made earlier.
