### ISSUE TITLE
is there any kind of documentation on centos 7?

### ISSUE THREAD

**Issue by adamramadhan** [codelucas/newspaper#114]
have anybody can get this working on centos 7? is there a step by step guide like ubuntu?

**Comment by codelucas** [comment]
At which point did you get stuck? Paste as many details as possible so we can help.

(Personally I've never used centos so there aren't any guides)

**Comment by adamramadhan** [comment]
nope everything working fine, but still need guide for those who dont know

**Comment by codelucas** [comment]
Do we need an installation guide? i.e., was it painful for you to set this library up on your machine?

If so, would you like to provide an installation guide? Otherwise I'll look into it.

**Comment by adamramadhan** [comment]
well i think not yet, but it sure could save people time, ok then let me see, ill open this when its ready to review

**Comment by codelucas** [comment]
:+1:
