### ISSUE TITLE
Getting rate limiting issue?

### ISSUE THREAD

**Issue by hoavt-54** [codelucas/newspaper#116]
Hi all,
First, thank you guys for very amazing tool.
I tried Newspaper to get list articles from a publisher by following the REAME file, however, the obtained significantly decline after each time I build the source.

`>>> import newspaper
>>> cnn_paper = newspaper.build('http://cnn.com')
No handlers could be found for logger "tldextract"
>>> print(cnn_paper.size())
222
>>> cnn_paper = newspaper.build('http://cnn.com')
>>> print(cnn_paper.size())
6
>>> cnn_paper = newspaper.build('http://cnn.com')
>>> print(cnn_paper.size())
1
`

Am I getting rate limitting or have I done somthing wrong? Thank you
Btw, here is the environment: Ubuntu 14.04, Python 2.7.6, newspaper for python2

**Comment by hoavt-54** [comment]
Sorry, I just found caching on the docs. Please close this.

**Comment by wscarano** [comment]
Newbie.  Also receiving this error. 
No handlers could be found for logger "tldextract"
Thanks.

**Comment by wscarano** [comment]
Great module!  Also receiving this error.

No handlers could be found for logger "tldextract"

for row in range(ws.nrows):
    # read second column URL only 
    url = ws.cell_value(row,1)
    # extract only primary domain name - not subdomain
    eresult = tldextract.extract(url)
