### ISSUE TITLE
Multi-threading article downloads not working

### ISSUE THREAD

**Issue by projectweekend** [codelucas/newspaper#12]
I am following the example at [http://newspaper.readthedocs.org/en/latest/user_guide/advanced.html#advanced](http://newspaper.readthedocs.org/en/latest/user_guide/advanced.html#advanced). After calling `news_pool.join()`, I then attempt to call `parse()` on an article belonging to a paper from the pool. It fails with the `ArticleException`: "You must download() an article before parsing it!".

**Comment by Shubhashri1310** [comment]
Hi neither I am getting any output nor am I able to print anything.  What do I do? Please Help


import newspaper
from newspaper import Article
from newspaper import news_pool

ct=0
l=[]
for i in parent_urls:
    ct+=1
    if cnt>11:
        break
    else:
        p=newspaper.build(i)
        a=Article(i)
        l.append(p)
        news_pool.set(l,threads_per_source=2)
        news_pool.join()
        a.parse()
        print(a.text)
        

---------------------------------- 
print(newspaper.__version__)-0.2.8
