### ISSUE TITLE
Is there a way to make it work by searching terms in news websites?

### ISSUE THREAD

**Issue by jannah** [codelucas/newspaper#122]
Hi,
First. I LOVE this API :)

I have a couple of questions:
1. Is it possible to scrape a site based on search term?
I am trying to scrape news articles based on a a search term on a news website (e.g. CNN). Right now, I am scraping URLs using kimono and then passing those URLs to newspaper. I think it would be great to have a way to scrape search results in addition to active content.
2. Can it bulk process a list of URLs using pooling? I am building my own thread pools using joblib now.

Thanks.

**Comment by codelucas** [comment]
Closing this because at the moment newspaper is more interested in improving core functionality and fixing bugs over extending features
