### ISSUE TITLE
Including Headers in Scraped text

### ISSUE THREAD

**Issue by jannah** [codelucas/newspaper#124]
Hi,
Is it possible to keep section headings or titles with the scraped text? 
I noticed that heading are omitted from fill text. 

Thank
Hassan

**Comment by mehuleo** [comment]
Hi,
You can use article['title'] to get the headline and you can also concatenate it with scraped text.
Keeping title in scraped text, makes it redundant.

**Comment by jannah** [comment]
Hi,
I am not referring to the article title but to subheadings/sections in the article. What I noticed is that those headings are dropped from the text.

**Comment by codelucas** [comment]
List an example URL so we can debug, subsections/titles are supposed to be in the article text

**Comment by codelucas** [comment]
Closing this because at the moment newspaper is more interested in improving core functionality and fixing bugs over extending features

**Comment by sutgeorge** [comment]
I would love to see this thing implemented as well.

**Comment by sutgeorge** [comment]
Hello, I would be interested in this feature as well (I will take the time to think of a solution at some point).
