### ISSUE TITLE
Login handling for premium websites

### ISSUE THREAD

**Issue by jmizgajski** [codelucas/newspaper#126]
It would be nice to be able to enable newspaper to log in to be able to look past paywals.

I don't have an idea yet how to do it automaticaly but the login url and payload could be sniffed in chrome "network" and then supplied to newspaper by hand.

[Here](http://stackoverflow.com/questions/13925983/login-to-website-using-urllib2-python-2-7)  are some ideas how to handle logins in urllib2 or with mechanize/selenium.

**Comment by codelucas** [comment]
An available way to do this would be to scrape directly from Google's cache. Usually even paywalled content allow Google's scrapers through to build the search index.

Reference: http://stackoverflow.com/questions/4560400/how-can-i-get-the-google-cache-age-of-any-url-or-web-page
