### ISSUE TITLE
Loading Pages that use heavy javascript

### ISSUE THREAD

**Issue by jannah** [codelucas/newspaper#127]
Hi,
I stumbled on a page that populates content using javascript. However, the extractor could not read it because the html was not rendered.
is there a way to make the page run in background so content is generated before extraction?
Thanks

**Comment by yprez** [comment]
@jannah , IMHO this is out of scope for this library.

I would try getting the pages with a headless browser, like phantomjs, then passing the resulting html to newspaper.

**Comment by jannah** [comment]
Thanks,
I actually used selenium to do it. It did the job.
