### ISSUE TITLE
Timeframe of news extracted

### ISSUE THREAD

**Issue by yyl** [codelucas/newspaper#133]
Very cool lib.

Wondering how old the scraped news could be by issuing generate_articles() or build()? Seems most of them are very recent. 

I am interested in archived news dated back to two or three years. Is there a way to specify the timeframe for news extraction?

**Comment by codelucas** [comment]
The code merely goes onto news domains and crawls for every identifiable news-looking URL via heuristics. How old the articles could be is dependent on the news domain. A big news company like CNN? Likely all are young.
