### ISSUE TITLE
Libray downgrading in installation

### ISSUE THREAD

**Issue by erickrf** [codelucas/newspaper#138]
I just installed newspaper via pip and noticed it downgraded some previously installed libraries:

- nltk went from 3.0.2 to 2.0.5.
- lxml went from 3.4.1 to 3.3.5
- requests went from 3.5.0 to 3.3.0
- six went from 1.8.0 to 1.7.3

This is weird. I don't think newspaper has any dependency specific to these older versions, does it?

**Comment by yprez** [comment]
The requirements.text files states the specific versions: https://github.com/codelucas/newspaper/blob/master/requirements.txt
I think that it would be much better if the requirements would list the minimal compatible versions, something like:
```
requests >= 3.2
nltk >= 3.0.0
# ...
```

@codelucas what do you think? I could make a PR for it if it's ok with you...

**Comment by glesica** [comment]
+1 The more immediate problem, though, is that the version in PyPi is (0.0.9.8). The latest version in the repo at least uses more current versions of nltk and requests (but still pins them exactly, which is a mistake IMHO).
