### ISSUE TITLE
get_publishing_date() doesn't fallback to raw regexes search?

### ISSUE THREAD

**Issue by dannguyen** [codelucas/newspaper#145]
via [newspapers/extractors.py#get_publishing_date()](https://github.com/codelucas/newspaper/blob/master/newspaper/extractors.py#L166) documentation:

        3 strategies for publishing date extraction. The strategies
        are descending in accuracy and the next strategy is only
        attempted if a preferred one fails.
        1. Pubdate from URL
        2. Pubdate from metadata
        3. Raw regex searches in the HTML + added heuristics
        
From what I can see, it looks like the search for publish_date ends with the iteration through `PUBLISH_DATE_TAGS`. I think raw regex search is a nice fallback and I've seen it done reasonably well in a [Ruby library named pismo](https://github.com/peterc/pismo).

The [relevant code](https://github.com/peterc/pismo/blob/master/lib/pismo/internal_attributes.rb):

```ruby
    # Return an estimate of when the page/content was created
    # As clients of this library should be doing HTTP retrieval themselves, they can fall to the
    # Last-Updated HTTP header if they so wish. This method is just rough and based on content only.
    MONTHS_REGEX = %r{(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|January|February|March|April|May|June|July|August|September|October|November|December)\.?}i
    DATETIME_REGEXEN = [
      /#{MONTHS_REGEX}\b\s+\d+\D{1,10}\d{4}/i,
      /(on\s+)?\d+\s+#{MONTHS_REGEX}\s+\D{0,10}\d+/i,
      /(on[^\d+]{1,10})\d+(th|st|rd)?.{1,10}#{MONTHS_REGEX}\b[^\d]{1,10}\d+/i,
      /\b\d{4}\-\d{2}\-\d{2}\b/i,
      /\d+(th|st|rd).{1,10}#{MONTHS_REGEX}\b[^\d]{1,10}\d+/i,
      /\d+\s+#{MONTHS_REGEX}\b[^\d]{1,10}\d+/i,
      /on\s+#{MONTHS_REGEX}\s+\d+/i,
      /#{MONTHS_REGEX}\s+\d+/i,
      /\d{4}[\.\/\-]\d{2}[\.\/\-]\d{2}/,
      /\d{2}[\.\/\-]\d{2}[\.\/\-]\d{4}/
    ]


    def datetime
      datetime = 10
      DATETIME_REGEXEN.detect {|r| datetime = @doc.to_html[r] }

      return unless datetime and datetime.length > 4
      # Clean up the string for use by Chronic
      datetime.strip!
      datetime.gsub!(/(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|mon|tues|tue|weds|wed|thurs|thur|thu|fri|sat|sun)[^\w]*/i, '')
      datetime.sub!(/(on\s+|\,|\.)/, '')
      datetime.sub!(/(\d+)(th|st|rd)/, '\1')
      Chronic.parse(datetime, :context => :past) || datetime
    end
```

As an example of where this regex approach succeeds: This Github Engineering post on Jekyll: http://githubengineering.com/browser-monitoring-for-github-com/ ...currently, __newspaper__ does not return a `publish_date` attribute, but __pismo__ succeeds...and it doesn't even use heuristics as far as I can tell, other than, find the first regex match for a date.

Although to speak specifically of the [Jekyll scenario](http://githubengineering.com/browser-monitoring-for-github-com/)...the standard template produces this HTML and CSS selector:

```html
<span class="post-date">May 19, 2015</span>
```

Perhaps there should be __4__  extraction strategies, with the 4th being raw regex, and the 3rd being body tag parsing? You could solve the problem for a huge number of standard Jekyll and Wordpress blogs by having a list of known HTML tags and selectors.

And hell, since __newspaper__ handles the HTTP request...maybe a 5th strategy should be to use the last-updated HTTP header? Yes, it's pretty unreliable...but maybe it's better than nothing? That said, with this many strategies, maybe it's worth it to include an attribute (e.g. `publish_date_info`) that is a __dict__, e.g.

```python
{ 'publish_date': datetime.datetime(2015, 5, 19, 0, 0), 'strategy': 'raw_regex', 'candidates': [list of other found dates] }
```
I know that making the API more complicated is not ideal...but in the case of publish date...this bit of metadata is _extremely_ helpful for curation/archiving activities, so it's arguably worth it. I'd argue the same for authors and the various strategies needed to extract bylines.

**Comment by dannguyen** [comment]
Oops I see this is a duplicate of #119

**Comment by codelucas** [comment]
Closing as it's a duplicate

**Comment by codelucas** [comment]
Thanks for identifying this however!
