### ISSUE TITLE
Found stop words for many languages !

### ISSUE THREAD

**Issue by javajack** [codelucas/newspaper#146]
I found stop words for some languages which are not yet supported in newspaper.
Is it feasible to add them so that something is better than nothing in those language support ?

https://code.google.com/p/stop-words/source/browse/trunk/stop-words/stop-words-collection-2014.02.24/stop-words/

**Comment by codelucas** [comment]
I'm more interested in improving core functionality and fixing bugs over extending features, thanks for finding this however!
