### ISSUE TITLE
Take local paths to .html files

### ISSUE THREAD

**Issue by xanderdunn** [codelucas/newspaper#153]
For datasets of already downloaded webpages as .html, it would be great to be able to do `Article('file://local/path/to/article.html')`.

**Comment by younes0** [comment]
a = Article('')
with open('Path/to/file', 'r') as f:
    html= f.readlines()
a.set_html(html)
a.parse()

**Comment by xanderdunn** [comment]
Oooo, thanks.  I've moved on from this project, so I can't readily test this, but it looks like it's what I needed.  Thanks!
