### ISSUE TITLE
Language Auto Detection

### ISSUE THREAD

**Issue by rbatukaev** [codelucas/newspaper#160]
Language auto detection does not work in most cases, when I have to deal with Russian articles. 

Hence, the article text is not available until I explicitly define language attribute.

What would you suggest?

**Comment by yprez** [comment]
Not really related to newspaper, but what I did in a similar case was detecting the language with langid (https://github.com/saffsd/langid.py) and then using newspaper with the language already selected.

**Comment by alon7** [comment]
Search for the string '"ru"' in the Russian article. 
Does it exist? If so, what tag is it? Post it here
Did you encounter the problem in more then one site?
Additionally, languid package will probably identify the language but as I saw on my benchmarks it is very slow

**Comment by codelucas** [comment]
Language "detection" is merely scanning some HTML tags and seeing if they give us the language and then defaulting to english otherwise. This is an unreliable method and you should just explicitly define if you know in advance.

This isn't high priority enough to leave open
