### ISSUE TITLE
Chinese not working

### ISSUE THREAD

**Issue by abhigenie92** [codelucas/newspaper#162]
from newspaper import Article
import pdb
from unidecode import unidecode
def get_article_newspaper(url):
	article = Article(url,en='zh') # Chinese
	article.download();
	article.parse()
	print unidecode(article.text).replace('Image caption','')

url='http://www.tyfzw.cn/?sw=774&b=177%20'
get_article_newspaper(url)

**Comment by codelucas** [comment]
I'd like more context, otherwise closing
