### ISSUE TITLE
Different extracted results from newspaper-0.0.8 and latest newspaper-0.0.9.8 in some urls

### ISSUE THREAD

**Issue by jyb002** [codelucas/newspaper#164]
I find 2 different version of newspaper have different results in some urls, and newspaper-0.0.8 is better.

I use the latest version newspaper-0.0.9.8. And results are shown as follows:
>>> url = "http://www.northjersey.com/news/nypd-man-sought-for-questioning-in-2-hotel-deaths-1.1410433"
>>> article = Article(url)
>>> article.download()
>>> article.parse()
>>> article.text
u"NYPD: Man sought for questioning in 2 hotel deaths\n\nAssociated Press\n\nNEW YORK (AP) \u2014 The New York Police Department says it's trying to locate a man for questioning in connection with the deaths of two women at hotels in Manhattan and Brooklyn.\n\nThe NYPD said Tuesday that it's seeking the public's help in finding 36-year-old Joseph Danclair of Brooklyn. He has a tattoo of praying hands on his right upper arm and a tattoo of a rose on his left upper arm.\n\nPolice say they believe Danclair had spent time with each of the women.\n\nThe 35 year-old woman was found dead on July 23 in Brooklyn's Bushwick Hotel.\n\nThe 43-year-old woman was found dead on Sept. 8 in the Manhattan Broadway Hotel on West 38th Street.\n\nA photo of the man being sought for questioning is on the NYPD Crimestoppers website."

Concerning newspaper-0.0.8, I use the demo: http://newspaper-demo.herokuapp.com, which is not updated yet.
And the result is:
NEW YORK (AP) — The New York Police Department says it's trying to locate a man for questioning in connection with the deaths of two women at hotels in Manhattan and Brooklyn. The NYPD said Tuesday that it's seeking the public's help in finding 36-year-old Joseph Danclair of Brooklyn. He has a tattoo of praying hands on his right upper arm and a tattoo of a rose on his left upper arm. Police say they believe Danclair had spent time with each of the women. The 35 year-old woman was found dead on July 23 in Brooklyn's Bushwick Hotel. The 43-year-old woman was found dead on Sept. 8 in the Manhattan Broadway Hotel on West 38th Street. A photo of the man being sought for questioning is on the NYPD Crimestoppers website.

The difference is "NYPD: Man sought for questioning in 2 hotel deaths\n\nAssociated Press\n\n" located before the first sentence of the actual text content in newspaper-0.0.9.8.

Anyone knows why latest version has a worse result of the extracted text content.
Thanks for help.

**Comment by codelucas** [comment]
I made changes in the extraction code around those versions. This was tested on many of articles and most of the time extraction was better. However there are edgecases and this is a valid issue! Thanks for reporting and I'll investigate

**Comment by codelucas** [comment]
The changelog is up, closing for now since we are discussing a previous version
