### ISSUE TITLE
Skipping text inside dropcap or wordpress custom short codes

### ISSUE THREAD

**Issue by anandaverma** [codelucas/newspaper#167]
```
<p class="su-dropcap su-dropcap-style-flat" style="font-size:1.5em">I am skipped</p>
```

"I am skipped" text is skipped when parsing.

**Comment by codelucas** [comment]
Thank you for filing this issue but this report does not nearly have enough context for me to debug.

How text is skipped or chosen into the final extracted summarized text format isn't just based on a single HTML tag, but the structure of HTML tags and many other tags around your text.
