### ISSUE TITLE
Downgrades to old versions of required packages upon installation

### ISSUE THREAD

**Issue by cartisan** [codelucas/newspaper#174]
The versions of the packages in requirements.txt are fixed with `==` .
This leads to the replacement of current versions of this packages with old ones upon installation of newspaper with `pip install newspaper`.

I would plead for using `>=` syntax for all required packages unless there is an important reason to use a specific version on single requirements. An nice example requirements.txt can be found here: https://github.com/scikit-image/scikit-image/blob/master/requirements.txt

**Comment by codelucas** [comment]
Good idea, doing this now. (Originally done with == to ensure no breakage on current setups, but that clearly isn't working with many recent issues being around version numbers).

**Comment by yprez** [comment]
+1
I can add this quickly (current versions and up should work).

**Comment by codelucas** [comment]
Go for it @yprez

**Comment by yprez** [comment]
@codelucas ping
