### ISSUE TITLE
Critical leak in newspaper.mthreading.Worker

### ISSUE THREAD

**Issue by alexanderlukanin13** [codelucas/newspaper#177]
Summary
-------------

Each call of `newspaper.build` or `newspaper.Source` constructor leaks memory and creates 20 hanging threads.

This goes unnoticed in simple crawlers, but in complex and long-living applications it eventually leads to crashing of Python process and possibly OS slowdown/crashing.

How to reproduce
----------------------

1. Create and activate a fresh virtualenv

        python3 -m venv newspaper-bug
        source newspaper-bug/bin/activate

2. Install newspaper 0.1.5

        pip install newspaper3k==0.1.5

3. Install objgraph for debugging

        pip install objgraph==2.0.1

4. Save following script as `script.py`

        import objgraph
        import newspaper

        for i in range(1, 1000000):
            print(i)
            s = newspaper.build('http://www.kingstonguardian.co.uk/news/',
                                memoize_articles=False)
            objgraph.show_growth()
            input()

5. Run the script `python script.py`. Wait a little. You will see something like this:

        1
        function                       5848     +5848
        dict                           3324     +3324
        tuple                          2081     +2081
        list                           1973     +1973
        weakref                        1649     +1649
        builtin_function_or_method     1303     +1303
        wrapper_descriptor             1230     +1230
        method_descriptor              1101     +1101
        getset_descriptor              1056     +1056
        type                            836      +836

    A lot of new objects are created for the new `newspaper.Source`. Seems okay, but...

6. Press ENTER to re-create the same Source second time.

        2
        dict                           3944      +620
        list                           2406      +433
        builtin_function_or_method     1471      +168
        frame                           203      +100
        deque                           153       +76
        Condition                       149       +74
        RequestsCookieJar               112       +56
        CaseInsensitiveDict             112       +56
        DefaultCookiePolicy             112       +56
        HTTPResponse                    112       +56

    Again, a lot of objects is created. Seems suspicious.

7. Press ENTER again

8. And again and again. Memory is growing.

9. But it's just the beginning of the story.

    Get PID of script process:

        ps ax | grep script.py

    And check out the number of threads it has

        ps Huhp <PID> | wc -l

After five steps of `script.py` (five `Source` objects created), the number of threads is:

    $ ps Huhp 10992 | wc -l 
    101

The cause
---------

This leak is caused by the following line:
https://github.com/codelucas/newspaper/blob/d8253bf2c60f601d965b77e521be0297874d69ac/newspaper/mthreading.py#L30

`Queue.get()` without timeout argument [blocks forever](https://docs.python.org/3.4/library/queue.html#queue.Queue.get) when queue is empty, making the thread hang forever. All associated Python objects also remain in memory.

**Comment by codelucas** [comment]
Holy crap @alexanderlukanin13 great find! I'll work a fix now. This also applies to python 2.X after looking at the docs.

**Comment by codelucas** [comment]
This is fixed in my latest commit: https://github.com/codelucas/newspaper/commit/4cc096fad6bd36429155ca60452a167c9bd9224e

**Comment by codelucas** [comment]
Will merge into pip ASAP
