### ISSUE TITLE
Install on Mac - El Capitan Failed - "Operation not permitted" 

### ISSUE THREAD

**Issue by theonlydaleking** [codelucas/newspaper#181]
If you're attempting to install on el-capitan, you'll see something like this: 

OSError: [Errno 1] Operation not permitted: '/tmp/pip-LRkhiJ-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

This is because el-capitan already has six installed and won't let you uninstall it. 

This worked for me instead: 

sudo pip install newspaper --ignore-installed six

**Comment by yprez** [comment]
You're using `six==1.4.1`, newspaper requires `six==1.7.3`. Doesn't sound like a bug imho.
