### ISSUE TITLE
Suggestion: extract social network profiles and other metadata

### ISSUE THREAD

**Issue by yprez** [codelucas/newspaper#185]
It would be nice if Newspaper would extract links to social media profiles, and perhaps other metadata when parsing articles.

E.g. Twitter uses the following tags:
```
<meta name="twitter:creator" content="@someone">
<meta name="twitter:site" content="@...">
```
Other social networks has similar ways of linking web pages pages to profiles. Anchor links can also be scraped.

I can try working on it if there's interest...
And assuming @codelucas would be interested in merging something like this.

**Comment by codelucas** [comment]
I would be interested in this

**Comment by yprez** [comment]
I'll close this for now under the new "no new features" policy :)

And because I have no time to work on this, and improving the extraction should be the higher priority.

@codelucas , how about adding a "Contribution guide" somewhere, that states what the projects priorities and wanted features are? This issue for example would probably be under "nice to have".
