### ISSUE TITLE
Feature: Named entity recognition from the article

### ISSUE THREAD

**Issue by makalaaneesh** [codelucas/newspaper#189]
**NLTK** has a named-entity feature. I think it would be a cool feature to extract the named-entities from the article text. 
I sent a PR #186 
@codelucas Can you please review it? :)

**Comment by codelucas** [comment]
See my comment on your PR. Thanks a lot for identifying this new feature and writing a PR but newspaper is prioritizing bugfixes and improving core functionality right now

**Comment by makalaaneesh** [comment]
@codelucas I totally understand. :)
