### ISSUE TITLE
Suggestion: maintain a changelog

### ISSUE THREAD

**Issue by yprez** [codelucas/newspaper#191]
Otherwise it's hard to keep track of what's changed between versions.

Might be a good idea to an automated tool for changelog generation.

Here's one list of them: https://allmychanges.com/help/changelog-generators/ maybe something there will make it easy.

This might prevent issues like #164 and make people feel safer about upgrading.

**Comment by alon7** [comment]
Sounds like a good idea :+1:

**Comment by yprez** [comment]
https://github.com/skywinder/github-changelog-generator seems work really well.

The only problem is that versions after 0.0.9 aren't tagged so it stuffs everything under "unreleased". 

Luckily it's easy to find where the tags should be with `git log newspaper/version.py`...

**Comment by yprez** [comment]
Tried with github-changelog generator.

Command I ran to install the generator and generate changelog:

```
gem install github_changelog_generator
export CHANGELOG_GITHUB_TOKEN=[YOUR_TOKEN_HERE]
github_changelog_generator -u codelucas -p newspaper
```

The result: https://github.com/yprez/newspaper/blob/cb6288ac83dde9cdac03418d04148b0fa2a19b84/CHANGELOG.md

Tagging the github issues (e.g. question / bug / duplicate / feature) can improve this a lot.

The missings tags are:
```
git tag 0.1.0 18836f
git tag 0.1.1 0289aa
git tag 0.1.2 3c7235
git tag 0.1.3 5c182e
git tag 0.1.4 baef15
git tag 0.1.5 48d666
git tag 0.1.6 3cedd7
```

**Comment by codelucas** [comment]
Hmm, I should've been better about tagging, this would make a lot of sense for this repo

**Comment by codelucas** [comment]
@yprez: I just pushed all 17 new tags  (0.1.7 was made today)  .. generating the changelog now

**Comment by codelucas** [comment]
Our changelog is live and committed! https://github.com/codelucas/newspaper/commit/126c6e01bb776f35a36a975649bd34aef62db1f0
