### ISSUE TITLE
Improving Threading

### ISSUE THREAD

**Issue by PandaXcentric** [codelucas/newspaper#201]
Hey, so I was looking at the multithreading file, and you use Python threads.  It might be more performant to use gevent (basically gets around the global interpreter lock).  Just a thought, if performance isn't really an issue here just ignore this :)

**Comment by yprez** [comment]
There are some benchmarks with multithreading gevent and asyncio: https://github.com/codelucas/newspaper/blob/master/tests/benchmarks.py
I didn't use the project back then so I have no idea what's the history with it or where it went.

By the way, as far as I know gevent doesn't really get around the GIL, in the way that it still runs everything in a single process / thread. It's intended for IO bound stuff, pretty much the same as Python threads...

**Comment by PandaXcentric** [comment]
you're right, it looks like gevent may still face the same constraints.  It seems like Jython or IronPython may be the only ways around it.

**Comment by yprez** [comment]
I don't think newspaper is very CPU intense, except maybe the nlp processing with nltk and such, so I don't think it's a major concern.

pypy might also offer some speedup (and no GIL on top), not sure if it will work on it though.
