### ISSUE TITLE
problem loading newspaper module

### ISSUE THREAD

**Issue by nahuelange** [codelucas/newspaper#206]
Loading the module I got this error:
```
/home/nahuel/workspace/newspaper/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in <module>()
     68 _openssl_versions = {
     69     ssl.PROTOCOL_SSLv23: OpenSSL.SSL.SSLv23_METHOD,
---> 70     ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
     71     ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
     72 }

AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

**Comment by yprez** [comment]
@nahuelange what version of newspaper are you using? at what step does this happen?

The latest (newspaper3k) version only supports Python 3, but if you're running that I think it would fail earlier...

If you're using the Python 2 version, maybe it's an outdated version of requests or urllib3... can you do a `pip freeze`?

**Comment by nahuelange** [comment]
I use last version for python2 (installed with pip install) in a virtualenv with no-site-packages.
This happen just after installing it, but now it's working…
