### ISSUE TITLE
Canonical link sometimes returns relative uri

### ISSUE THREAD

**Issue by yprez** [codelucas/newspaper#227]
```
import newspaper
a = newspaper.Article(url='https://www.born2data.com/2016/fast-API-with-Bottle.html')
a.download()
a.parse()

a.url
#[Out]# 'https://www.born2data.com/2016/fast-API-with-Bottle.html'

a.canonical_link
#[Out]# '/2016/fast-API-with-Bottle.html'
```

In this case it's a problem with the `og:url` tag:

```
<meta property="og:url" content="/2016/fast-API-with-Bottle.html">
```

These should be converted to the absolute url or filtered out.

**Comment by yprez** [comment]
Apparently the code for this was already present, but I left it applied only to rel=canonical, and not to og:url when working on #204

**Comment by adamn** [comment]
Any update on this?  Would be nice to get it in

**Comment by yprez** [comment]
@adamn #228 is supposed to fix it, can you take a look at it? (just to make sure I didn't mess anything up)

I'm usually a bit wary about merging my own pull requests, but I guess this one can be an exception...
