### ISSUE TITLE
Installation: import news paper; No module named parse

### ISSUE THREAD

**Issue by oliviac12** [codelucas/newspaper#229]
I was trying to install newspaper by using source code and ran the requirements.txt and setup.py. everything seems fine, but after I ran 
`git clone git://github.com/codelucas/newspaper.git`
`pip install -r requirements.txt`
`python setup.py install`
And try to do import newspaper, keep saying No module named parse. 

I am using OSX. 

Thank you so much.

**Comment by sirrryankennedy** [comment]
You should try using python 3. OS X comes installed with python v. 2.7.10 I believe. You can check your version like this
`python --version` then try
`python3 --version`

If that second line doesn't work, you need to install python 3 and run .py files with 

`python3 your_file.py`

**Comment by yprez** [comment]
I'll assume it's resolved. @oliviac12 feel free to reopen if you're still having issues.
