### ISSUE TITLE
Natural Language of Chinese 

### ISSUE THREAD

**Issue by Blusea** [codelucas/newspaper#230]
When runing `pip install newspaper` on Windows， I fond the jieba packages was depented and installed, which is a package to deal with the Chinese natural  language. So how we can use the package with your project?

**Comment by yprez** [comment]
@Blusea not sure what you mean... do the examples in the readme work for you?

**Comment by yprez** [comment]
@Blusea , feel free to reopen if you come back here and still having problems :)
