### ISSUE TITLE
Download can be extremely slow for particular URLs

### ISSUE THREAD

**Issue by hangll** [codelucas/newspaper#231]
This happens even after setting request_timeout. For example:
https://business.linkedin.com/content/dam/business/marketing-solutions/global/en_US/site/pdf/cs/linkedin_hnw_investor_research_us_en_130314.pdf?utm_content=buffer0eabd&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by hangll** [comment]
After debugging a little while, it seems that when the response is a large pdf, this line is extremely slow to execute:
https://github.com/codelucas/newspaper/blob/master/newspaper/network.py#L58

**Comment by yprez** [comment]
@hangll how would you check that it's a pdf? content-type header?

**Comment by hangll** [comment]
@yprez From the [response](https://github.com/codelucas/newspaper/blob/master/newspaper/network.py#L54), you can get the content type. Actually I find this problem more general (not specific to pdf). For instance, certain website can be extremely slow (maybe with videos) and the python request lib doesn't guarantee that the whole function gets returned within timeout. So I use [eventlet](eventlet.net) to wrap the everything.

**Comment by yprez** [comment]
@hangll I'm doing something similar myself with gevent. The timeouts in "requests" aren't really helpful here...
