### ISSUE TITLE
Newspaper logo

### ISSUE THREAD

**Issue by vintageshinpads** [codelucas/newspaper#236]
Can you please also include a way to get the image file(url) of newspapers logo? Just like description.

**Comment by yprez** [comment]
@vintageshinpads not sure what you mean, can you explain further?

**Comment by alon7** [comment]
I think he meant every news site has an official logo, he wants newpaper3k
to get it as well.
In my personal opinion, I think it will be pretty hard because there is no
standard

**Comment by yprez** [comment]
Oh, yeah, if that's the case I agree... it'll be very hard to get the site's logo...
The `top_image` parameter is the closest thing I can think of - it's (almost) the same thing most social networks are getting the image from when posting.
