### ISSUE TITLE
Trying to exclude sentences containing certain words from extracted article

### ISSUE THREAD

**Issue by Sgroove** [codelucas/newspaper#238]
I'm adding stop words that I want to be skipped when extracting the article in the cleaners.py file but nothing happens. Does anyone know where should I add them if I don't want let's say a sentence containing the word "**stocks**", to be extracted from the article.

**For example:**
"It's another source of demand for stocks, and presumably from smart buyers," he said. "It's lent some optimism to the market."

**would just return:**
It's lent some optimism to the market.

Thanks!

**Comment by yprez** [comment]
I think that what you're trying to do isn't in the scope of newspaper, and isn't implemented...

Maybe you can split the text into sentences with `newspaper.nlp.split_sentences()` after getting the text and manually filtering those...

**Comment by Sgroove** [comment]
I see. Thanks yprez. That could be a great feature to have though if we want to filter out trademarks or unwanted words.
