### ISSUE TITLE
Is newspaper.build method deterministic?

### ISSUE THREAD

**Issue by ijkilchenko** [codelucas/newspaper#243]
Whenever I call `newspaper.build`, I often get different results in the number of articles. If I'm lucky, I get A TON of articles, but sometimes I get very few or none at all. 

I have been trying this with cnn and I get very different results from one minute to the next and I am not sure what's wrong. 

I tried this using `newspaper` as installed from pip and I also set up this repository's clone and downloaded all the prerequisites inside of virtualenv. Still same results. 

I am not sure what else I can describe. 

All tests are passing (5 are skipped though). 

This is what I am experiencing. 

```
>>> import newspaper
>>> p = newspaper.build('http://cnn.com')
>>> for article in p.articles:
...     print(article.url)
... 
http://cnn.com/2016/05/06/technology/panama-papers-search/index.html
>>> p = newspaper.build('http://cnn.com')
>>> for article in p.articles:
...     print(article.url)
... 
http://cnn.com/2016/05/06/opinions/sadiq-khan-london-mayor-ahmed/index.html
http://money.cnn.com/2016/05/06/news/economy/london-mayor-sadiq-khan/index.html
http://money.cnn.com/2016/05/06/news/economy/london-mayor-sadiq-khan/index.html?section=money_topstories
http://money.cnn.com/2016/05/05/news/verizon-strikes-temporary-relocation/index.html?section=money_topstories
http://cnn.com/2016/05/06/europe/uk-london-mayoral-race-sadiq-khan/index.html
>>> 
```

5 minutes later...

```
>>> import newspaper
>>> p = newspaper.build('http://cnn.com')
>>> for article in p.articles:
...     print(article.url)
... 
http://cnn.com/videos/health/2016/05/06/teen-pageant-contestant-collapses-on-stage-pkg.kvly/video/playlists/cant-miss/
http://cnn.com/2016/05/06/news/economy/london-mayor-sadiq-khan/index.html
>>> p = newspaper.build('http://cnn.com')
>>> for article in p.articles:
...     print(article.url)
... 
>>> # nothing... 
```

**Comment by yprez** [comment]
Not sure what's going on, except that maybe cnn is blocking the 2nd request somehow...

**Comment by ijkilchenko** [comment]
I get the same behavior with other websites, too. 

I also tried using the lower level Source object instead and set the number of threads to 1. Still same thing is happening. 

I should also mention that just using the Article object to download, parse, and nlp individual links seems to work fine. 

I'll try to reproduce this bug(?) on my other laptop.

**Comment by B0nzo93** [comment]
The same goes for me! I'm experiencing exactly the same issue on my system. Tried different news web sites sometimes I might get all articles, but most of the time the return is an empty list. Of course "build()" can't be deterministic as news websites change, but theres definitly somethin going wrong here.

**Comment by ijkilchenko** [comment]
Glad I am not crazy. Just out of curiosity, B0nzo93, what kind of computer are you using? I am doing this on the 2015 Macbook -- I am wondering if this has to do with the multithreading.

**Comment by B0nzo93** [comment]
A Dell Inspron 15 7559 running Windows 10. So I don't think it's our systems. Was there a new (major) release of any library newspaper3k depends on in the last days/hours? I installed newspaper3k with pip using Anaconda Python 4.0 (Python 3.5.1, 64 bit) a few hours ago. I'm experiencing this issue since one or two hours now. It seemed to work fine the at first.

**Comment by B0nzo93** [comment]
Anything new on this? Today I got:

```
cnn = newspaper.build("http://cnn.com")
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\newspaper\parsers.py", line 65, in fromstring
    if html.startswith('<?'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
[Source parse ERR] http://cnn.com
```
I didn't get this for other news web pages I tried, but again most of the times the article list was empty or the results were pretty undeterministic and changing completly from call to call.

**Comment by ijkilchenko** [comment]
@B0nzo93 I still would love for the `build` method to work, however, I have switched to only using the `Article` call on a given url. Since the `build` method works so poorly for me, I am finding all the links myself and then calling `Article` on each url that I find -- this is my workaround for now. I am hoping that in the future I'll be able to replace this by something that figures out articles on a given page a bit better than just looking at all the links (I am currently considering doing some machine learning).

**Comment by yprez** [comment]
@ijkilchenko , that's what I was doing since I started using the library, so I didn't notice the weird behavior with `build`.
Do you have examples of other sites besides cnn where it fails? They have so many articles that it'll be hard to keep track.

@B0nzo93 never seem this exception before, looks like it happened before all the "source" processing stuff because the html wasn't converted to unicode in parsers.py... did you manage to trigger it more than once?

**Comment by yprez** [comment]
@ijkilchenko @B0nzo93 after looking atto build() a little bit, I think it's related to caching...

http://newspaper.readthedocs.io/en/latest/user_guide/quickstart.html#article-caching

Can you try reproducing it with caching disabled?

e.g. `cnn = newspaper.build('http://cnn.com', memoize_articles=False)`

I'm getting 768 articles from cnn every time I run this...
It's either a bug with how caching works or simply the default behavior, not sure which since I never used build() before.

**Comment by ijkilchenko** [comment]
@yprez Hey! That looks very promising! I think turning off memoization fixes it for me. 

Here's some output. 

```
>>> cnn = newspaper.build('http://cnn.com', memoize_articles=False)
>>> len(cnn.articles)
1075
>>> cnn = newspaper.build('http://cnn.com')
>>> len(cnn.articles)
248
>>> cnn = newspaper.build('http://cnn.com')
>>> len(cnn.articles)
0
>>> cnn = newspaper.build('http://cnn.com', memoize_articles=False)
>>> len(cnn.articles)
1075
>>> cnn = newspaper.build('http://cnn.com', memoize_articles=False)
>>> len(cnn.articles)
1075
```

**Comment by ijkilchenko** [comment]
So I guess everything is actually working as expected now that I am aware of caching. 

Here's a little experiment. I compare whether calling `build` returns anything the second time that was not returned the first time. If it doesn't, then the caching works as expected. I also do this experiment with caching turned off and see that some urls are the same between calling it the first and second time. 

```
>>> import newspaper
>>> cnn1 = newspaper.build('http://cnn.com')
>>> urls1 = set([article.url for article in cnn1.articles])
>>> cnn2 = newspaper.build('http://cnn.com')
>>> urls2 = set([article.url for article in cnn2.articles])
>>> urls1.intersection(urls2)
set() # no urls are shared between calls when caching is on
>>> cnn1_fresh = newspaper.build('http://cnn.com', memoize_articles=False)
>>> urls1_fresh = set([article.url for article in cnn1_fresh.articles])
>>> cnn2_fresh = newspaper.build('http://cnn.com', memoize_articles=False)
>>> urls2_fresh = set([article.url for article in cnn2_fresh.articles])
>>> len(urls1_fresh.intersection(urls2_fresh))
1078 # same same urls are returned because caching is on
```

I guess I should have RTFM'ed first. Closing issue.

**Comment by Sashkow** [comment]
If data is cached when memoize_articles=True then how do I invoke cached cached data?
