### ISSUE TITLE
Failing to extract article in simple website

### ISSUE THREAD

**Issue by DavidVentura** [codelucas/newspaper#247]
Currently newspaper fails to extract 
`https://googleblog.blogspot.com.ar/2016/05/translate-where-you-need-it-in-any-app.html`

Which is a very simple site. I'll see if I can fix the extractor to match this site. How would I test that I'm not breaking any other site after modifying it?

**Comment by yprez** [comment]
For some reason it's seeing the caption as the main div of the article.

Probably happens here somewhere: https://github.com/codelucas/newspaper/blob/ac5f7c8596cc4cbbeacd4af5e65bcd05ce8079b6/newspaper/extractors.py#L739

**Comment by yprez** [comment]
Regarding breaking other articles, the fulltext tests should cover that...

**Comment by yprez** [comment]
I noticed that the main body of the article is marked with `itemprop="articleBody"` (https://schema.org/articleBody)

Could be a nice improvement to look for this element first, and if found, select it as the main node.
