### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by mavarick** [codelucas/newspaper#259]
when i import newspaper in ipython, it turns out:
In [3]: import newspaper
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-3d891fe45a25> in <module>()
----> 1 import newspaper

/Users/mavarick/anaconda/lib/python2.7/site-packages/newspaper/__init__.py in <module>()
      8 __copyright__ = 'Copyright 2014, Lucas Ou-Yang'
      9
---> 10 from .article import Article, ArticleException
     11 from .api import (build, build_article, fulltext, hot, languages,
     12                   popular_urls, NewsPool, Configuration as Config)

/Users/mavarick/anaconda/lib/python2.7/site-packages/newspaper/article.py in <module>()
     10 import glob
     11
---> 12 from . import images
     13 from . import network
     14 from . import nlp

/Users/mavarick/anaconda/lib/python2.7/site-packages/newspaper/images.py in <module>()
     13 import io
     14 import traceback
---> 15 import urllib.request
     16 import urllib.parse
     17 import urllib.error

ImportError: No module named request

What's Wrong?

**Comment by yprez** [comment]
How did you install newspaper? It looks like the newspaper3k version which doesn't support Python 2...

**Comment by mavarick** [comment]
yeah，it only support python3, it works well in python3 env.
