### ISSUE TITLE
Article list not printing consistently

### ISSUE THREAD

**Issue by Superraptor** [codelucas/newspaper#264]
Hey, really sorry if this is a dumb question, but I'm running the following script, based on the example:

```
import newspaper

def main():
  cnn_paper = newspaper.build('http://cnn.com')
  for article in cnn_paper.articles:
    print(article.url)

if __name__ == "__main__": main()
```

it worked once, then not at all (after about 20 runs, after that I fiddled with the code, then changed the code back). After changing it back, it printed one URL. The next five times, no URLs were printed.

I guess I'm just curious if this is: (1) something I did (a missplaced dependency?), (2) something the program did (some sort of bug... no idea), or (3) a rate-limit feature by CNN (I don't think this is the case because I doubled checked the above code with CBS News and USA Today and also received no URLs in return after running 10 times a piece).

Any help would be much appreciated!

**Comment by yprez** [comment]
Hey,
Try disabling caching with `newspaper.build('http://cnn.com', memoize_articles=False)`

http://newspaper.readthedocs.io/en/latest/user_guide/quickstart.html#article-caching

**Comment by Superraptor** [comment]
Wow! I can't believe I missed that! Thank you so much, it worked perfectly!
