### ISSUE TITLE
Article exception errors with Wall Street Journal

### ISSUE THREAD

**Issue by Superraptor** [codelucas/newspaper#266]
I've been trying to parse wsj.com files using the following script:

```
def news_vocab(url, memo):
  paper = newspaper.build(url, memoize_articles=memo)
  articles = []
  article_vocab = []
  for article in paper.articles:
    print(str(article.url).encode('utf-8'))
    try:
      ar = Article(article.url)
      art = []
      ar.download()
      ar.parse()
      authors = ar.authors
      article_text = ar.text
      ar.nlp()
      keywords = ar.keywords
      summary = ar.summary
      art.append(authors)
      art.append(article_text)
      art.append(keywords)
      art.append(summary)
      articles.append(art)
    except:
      print("Article exception error.")
  return articles
```

Some of the URLs I've received the error on are:
- http://www.wsj.com/articles/open-water-vs-flat-water-rowing-whats-the-difference-1467639001?tesla=y
- http://www.wsj.com/articles/new-california-law-lowers-the-bar-for-gun-seizures-1467409616
- http://www.wsj.com/news/world/middle-east

I'm not really sure how to go about diagnosing this error, so any would be much appreciated!

**Comment by yprez** [comment]
Hi, first we need to know what exception you're getting...
Can you try running the same without the try/except block, and post the result?

On a general note - a raw `except:` without any output or logging is never a good idea... it will swallow any exceptions including stuff resulting from simple typos, or pressing ctrl+c to stop the execution, etc.
In this case it makes it impossible to debug.
Assuming you want to catch *all* exceptiions, it's probably a good idea to change the except block to something that prints or logs the actual exception and traceback, for example:

```python
import traceback

try:
    print('do stuff here')
except Exception as e:
    print(e)
    traceback.print_exc()
```

**Comment by Superraptor** [comment]
I think you're right! I've run about 200 articles and have not run into an error... I think it was a misplaced package import!
