### ISSUE TITLE
top_image same as url on the python 3.5.2

### ISSUE THREAD

**Issue by vizigin** [codelucas/newspaper#287]
Hi,

This [demo](http://newspaper-demo.herokuapp.com/) worked under python 2.7.12. It correctly returns top_image.

I deployed [demo](https://intense-castle-45739.herokuapp.com/) with python 3.5.2. It returns top_image same as URL.

URL is: http://swiftbook.ru/tutorials/alamofire-getting-started

**Comment by yprez** [comment]
The latest version on Python 3.5 returns the correct image. What version were you using?
