### ISSUE TITLE
How often to run newspaper. 

### ISSUE THREAD

**Issue by wokandroll** [codelucas/newspaper#294]
@codelucas 
I am just wondering how often to run the newspaper. Every few minutes , hour or day. I plan to crawl over maybe 100 news sources and populate a database with any news articles that are not already in the db.

**Comment by adamn** [comment]
This is not an appropriate question for a ticket.  Check out [StackOverflow's Newspaper section](http://stackoverflow.com/questions/tagged/newspaper)

**Comment by yprez** [comment]
Depends on your application... I wouldn't run it more often than once every hour to avoid getting blocked. So, somewhere between once an hour, once a day should work.

But yeah, this doesn't have much to do with the library...

**Comment by yprez** [comment]
Why don't just use it when you actually need the new articles?
