### ISSUE TITLE
Add extraction publishing date from article.

### ISSUE THREAD

**Issue by codelucas** [codelucas/newspaper#3]
The publishing date of an article is critical. I believe a good way of extracting publishing dates is to use a set of regex patterns and/or some notable id/class names.

**Comment by adamramadhan** [comment]
yeah i think we should put it somewhere in language regex.

**Comment by codelucas** [comment]
This issue is resolved:
https://github.com/codelucas/newspaper/commit/30eab17a49eb484420c65f347aa728b2515969ae

I've tested it on 150 different articles on various domains and it has a 60% success rate. (it could be even higher, up to 90%, but at a sacrifice for accuracy, but for publishing date the accuracy must be precise).

The publishing date extraction technique used relies on parsing dates out of the URL or metadata, which has a higher accuracy than regexing the HTML and using heuristics to choose a proper date.
