### ISSUE TITLE
Parse from a string instead of URL

### ISSUE THREAD

**Issue by Bartvds** [codelucas/newspaper#300]
I see no interface to parse from a user-supplied string of HTML. Because of #299 we can't use the regular downloader so I thought we could load text ourselves and pass the HTML to an Article but it doesn't seem to be possible?

**Comment by ranihorev** [comment]
Take a look at this:
https://github.com/codelucas/newspaper/issues/291

**Comment by dustyny** [comment]
I'm not sure #291 answers this question. I can give you a super easy work around.. I do think it's worth having a way to way to pass a file directly to newspaper. Something like newspaper.Article(file='html_data/filename.html') would be very helpful. 

I started a local http server using  `python3 -m http.server` from the directory that contains my html files. 

`import os
html_files_list = os.listdir('your_html_file_dir')
html_srvr = 'http://localhost:8000'

for file_name in html_files_list:
    current_url = html_srvr + file_name
    newspaper_function(current_url)
`

**Comment by Bartvds** [comment]
We ended up using a http cache kinda like @dustyny suggestion. #291 seems a fair workaround but what I would expect is a nice constructor argument like `Article(html=my_html)`.

**Comment by dustyny** [comment]
I'm not entirely sure I followed the suggestion in #291. Is the trick to use ```article.set_html(html)```?

**Comment by Bartvds** [comment]
Pass any url and call `set_html(html)` (instead of `download()`), then parse etc. 

I added a documentation PR #307

**Comment by yprez** [comment]
Yep, something like:

```python
    article = newspaper.Article(url=url)
    article.set_html(html)
    article.parse()
    article.nlp()
```

**Comment by iwpnd** [comment]
There is one thing you need to keep in mind. The parser is looking for a paragraph with a lot of stop words in it. That's why you add `'en'` to `fulltext(my_html, 'en')`. If there is no significant threshold (?) of stop words, the paragraph will not be identified as the relevant text body you want to parse and results in `AttributeError: 'NoneType' object has no attribute 'xpath'`.

You can try to use `from newspaper import fulltext` to:

```python
from newspaper import fulltext
my_html='''<!DOCTYPE html>
<html>
<body>
<p>My first paragraph is a story about a little girl and it's pony called flufferbottom.</p>
</body>
</html>'''
text = fulltext(my_html, 'en')
print('text')
# >> "My first paragraph is a story about a little girl and it's pony called flufferbottom."
```

or use it like your example:

```python
import newspaper
my_html='''<!DOCTYPE html>
<html>
<body>
<p>My first paragraph is a story about a little girl and it's pony called flufferbottom.</p>
</body>
</html>'''
article = newspaper.Article(url='http://example.com/test-url')
article.set_html(my_html)
article.parse()
print(article.text)
 # >> "My first paragraph is a story about a little girl and it's pony called flufferbottom."
```
