### ISSUE TITLE
How to use a proxy while downloading articles?

### ISSUE THREAD

**Issue by vu3jej** [codelucas/newspaper#317]
I couldn't find any information on the documentation as to how to set a proxy with `requests` while downloading the web pages for content extraction. Is there a configuration currently implemented to support this feature? If not, which part of the code shall I look into to customise to support this functionality? Thanks!

**Comment by xeriab** [comment]
You can edit the `get_request_kwargs` function located at `network.py` to look something like:

```python
def get_request_kwargs(timeout, useragent, proxies):
    """This Wrapper method exists b/c some values in req_kwargs dict
    are methods which need to be called every time we make a request
    """
    return {
        'headers': {'User-Agent': useragent},
        'cookies': cj(),
        'timeout': timeout,
        'allow_redirects': True,
        'proxies': proxies
    }
```
and pass proxies dict to the function

```python
proxies = {
    "http": "10.10.1.10:3128",
    "https": "10.10.1.10:1080",
}
```

Reference: [http://docs.python-requests.org/en/master/user/advanced/](url)

**Comment by vu3jej** [comment]
@xeriab Thanks!
