### ISSUE TITLE
Restrict download urls to domain/country?

### ISSUE THREAD

**Issue by dreamk73** [codelucas/newspaper#322]
If I want to download articles from a certain domain, I want to make sure it doesn't follow links to a website in another country and download text from there. Using the language tag does not prevent this from happening. For instance, when I use zdnet.fr, it downloads a few articles and then goes to zdnet.de, which I have no need for. Is there a solution?

**Comment by yprez** [comment]
Newspaper doesn't support this.

I would try to build the article list manually, and then check that the domains of the articles you collected match what you want (e.g. contains ".fr"). Does this help?
