### ISSUE TITLE
could i parse an article without downloaded 

### ISSUE THREAD

**Issue by YZLong** [codelucas/newspaper#359]
i got huge number of web pages with scrapy , those pages comes from different domains with various web styles , so it's hard for me to extract useful data one by one . could i use newspaper to deal with this problem .
i noticed that newspaper has cache fuction in the document , does it available now ?

**Comment by mercuree** [comment]
```python
article = Article(url) # url can be any string

f = open('file.html', encoding='utf-8')
article.download(html=f.read())
article.parse()
print(article.text)
```

**Comment by YZLong** [comment]
thank you very much @mercuree

**Comment by theSage21** [comment]
Also read https://github.com/codelucas/newspaper/issues/74. That might work.
