### ISSUE TITLE
"No module named 'newspaper'" after installation? 

### ISSUE THREAD

**Issue by Marthorax** [codelucas/newspaper#366]
Running on Mac OS X. 

Installed newspaper3k without a hitch, however, iPython won't recognize newspaper as a module. Any solutions? 

Specifically, the code it can't run is: from newspaper import Article

**Comment by yprez** [comment]
Not really familiar with OS X... did you install both newspaper and ipython in the same env?

**Comment by leenabharambe** [comment]
I installed newspaper on ubuntu. but same error occurred to me too.
What to do?

**Comment by codelucas** [comment]
Hello @Marthorax and @leenabharambe, I'd like to replicate the exact sequence of events of your installation to get your error to help debug it.

What command(s) did you use to install? What OS do you use? Please paste everything and be as descriptive as possible. Thanks.

**Comment by JSONValidator** [comment]
On macOS we need use `python3 file.py`, not `python file.py`.

**Comment by codelucas** [comment]
Good point @JSONValidator, this is probably a common mistake that's been happening.

We should inject in python3 or python2 version checks in the top level newspaper module so people get a more readable error "You are using the wrong python version" instead of a cryptic import error.

**Comment by kerchner** [comment]
I'm working in a Jupyter iPython notebook, with Python 3, but experiencing the issue here where even after a successful `pip3 install newspaper3k`, running `import newspaper` results in `ModuleNotFoundError: No module named 'newspaper'`.

I verified that `!python --version` returns `Python 3.6.0 :: Anaconda custom (x86_64)`

Any suggerstions, @codelucas ?  Thanks!  I'm excited to try this package.

**Comment by galaxydirector** [comment]
Same issue...

**Comment by JimmyCollins** [comment]
Same issue here on Windows, even after successful installation when I try to import in my Jupyter notebook I see this error message.

**Comment by Cyfy-max** [comment]
Same with @kerchner
