### ISSUE TITLE
Download Failing on Existing Articles

### ISSUE THREAD

**Issue by Helw150** [codelucas/newspaper#374]
I am extracting HTML out of an existing database of articles. However when I run `
        tmp = newspaper.Article(article)
        tmp.download()
        tmp.parse()
`
a not insignificant number of these articles pop up the warning: ```You must `download()` an article before calling `parse()` on it!``` even if these articles are not 404 links. I think the route cause must be something to do with slow page load time on this content, but would appreciate any help debugging.

#### https://www.voxcreative.com/sponsored/hub/bp-what-drives
-----------------
#### https://www.bloomberg.com/news/sponsors/samsung/wearable-tech-brings-business-to-your-wrist/?adv=6704&prx_t=hg4CAC8oFAM0ANA&prx_ro=s&ntv_fr
-----------------
 #### https://www.buzzfeed.com/macys/amazing-prom-looks-for-your-whole-party-squad?utm_term=.rl1bpoBAW#.ss3PbRYGA
-----------------
#### https://www.usatoday.com/story/sponsor-story/motley-fool/2016/11/29/why-microsoft-and-ge-cant-keep-up-stock/94339166/

**Comment by Helw150** [comment]
They were 403'ing to avoid crawlers.

**Comment by codelucas** [comment]
This is still an issue though, (the api should be clearer that the 4xx happened) We are going to fix this in another task

**Comment by codelucas** [comment]
The ideal situation after a 4xx happens in download() is parse() runs but gives a warning that the link 403ed. That would allow the dev to do things like change the rate that they are sending requests to the server, maybe lower it. Or maybe changing the user-agent or avoiding the news domain all-together

**Comment by Helw150** [comment]
@codelucas I closed it since the discussion of that API change seems to be going on in https://github.com/codelucas/newspaper/issues/357 but yeah, I definitely agree a warning on 403 would be great. Once I figured out it was 403, it was easy enough for these ones to be fixed by changing the headers in my request.

**Comment by iShekhar** [comment]
Same for http://www.baikal-daily.ru/news/16/266815/
Traceback (most recent call last):
You must `download()` an article first!
