### ISSUE TITLE
`cannot import name '_imaging'`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [codelucas/newspaper#377]
Hi, I have no problems on my Mac, but I trying to use `newspaper` on AWS Lambda. I tried few times to deploy a zip with my script and `newspaper` with all dependencies inside - getting libs in one directory using `pip3 install newspaper3k --target .` and second try with`virtualenv` as it described in the[ documentation about deployment to the Lambda](http://docs.aws.amazon.com/lambda/latest/dg/with-s3-example-deployment-pkg.html#with-s3-example-deployment-pkg-python), but Lambda return:

`cannot import name '_imaging'`

**Comment by vitaly-zdanevich** [comment]
Sorry, the problem was that I did not read the documentation carefully.

**Comment by iamparth** [comment]
Hi, if you could please explain what were you doing wrong. I am getting the same error and have almost tried everything.
Thanks!
