### ISSUE TITLE
TypeError: 'int' object does not support item assignment

### ISSUE THREAD

**Issue by fhamborg** [codelucas/newspaper#379]
Running on Python 3.5 (Linux)

```
[...]
  File "/home/andreas/Envs/newsi/lib/python3.5/site-packages/newspaper/article.py", line 219, in parse
    meta_data = self.extractor.get_meta_data(self.clean_doc)
  File "/home/andreas/Envs/newsi/lib/python3.5/site-packages/newspaper/extractors.py", line 514, in get_meta_data
    ref[part] = value
TypeError: 'int' object does not support item assignment
```

**Comment by codelucas** [comment]
Thanks for finding this!

**Comment by codelucas** [comment]
Will investigate, there seems to be a few errors in the html parse/extract logic

**Comment by codelucas** [comment]
The latest fix by @megatron-me-uk at https://github.com/codelucas/newspaper/pull/426 should fix your issue :) Please pull the latest master version of newspaper and reattempt this.

Otherwise, I plan on bumping the newspaper version and updating sometime this week.
