### ISSUE TITLE
Q: Is there anyway to build a newspaper but just get an specific amount of articles?

### ISSUE THREAD

**Issue by dp-DanielCastillo** [codelucas/newspaper#415]
I would like to get less articles from build() to speed loading time.
memoize isn't an option so I have it disabled by default

**Comment by fengkaijia** [comment]
Use: ```newspaper.build(url, limit=100)```

**Comment by N2ITN** [comment]
This is not working for me. 

````python src = newspaper.build(self.url, fetch_images=False, request_timeout=3, limit=30, memoize_articles=False)
print(len(src.articles))```
`>>> 785`

**Comment by N2ITN** [comment]
I made a fork where the value set by limit in `newspaper.build(url, limit=n)` dictates the amount of article urls scraped in `source.categories_to_articles()` and `source.feeds_to_articles()`. 

Looks like you are overwhelmed with pull requests but why not one more. It only adds 6 or so short lines of code, and makes getting 30 articles 5 times faster than before.
