### ISSUE TITLE
Add possibility/method to keep images along with text

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [codelucas/newspaper#451]
When I give 

`article = Article( post.link )`
`article.download()`
`article.parse()`
`text = article.text`

I want to still be able to keep the images and some basic formatting like b, i,a,  ul tags, while eliminating all the garbage like div span.
I want to feed this output to telegra.ph API (the anonymous blog from telegram)

Thanks

**Comment by mercuree** [comment]
https://github.com/Kylmakalle/TelegraPyBot/blob/master/Telegra.py
Look at this sample project

**Comment by jl-DaDar** [comment]
Yes, the images should be kept in article because a lot of time the text and the images goes hand in hand.

**Comment by codelucas** [comment]
Thanks for answering the question @thoraxe, please use `article_html`
