### ISSUE TITLE
Cache folder settings should be optional/configurable.

### ISSUE THREAD

**Issue by jeffnappi** [codelucas/newspaper#46]
Newspaper currently creates its cache-folder under ~/.newspaper_scraper. This should be a configurable option and should be able to be disabled altogether for those not using the 'memoized' functionality of newspaper.

**Comment by tquach** [comment]
Has this been resolved?

**Comment by codelucas** [comment]
Once again, thanks for identifying this but newspaper is prioritizing bugfixes and improving core functionality right now so I'm closing

**Comment by mhamann** [comment]
I know this is old, but it limits running newspaper in certain environments. This really should be re-opened if it's something you plan on fixing. Closing issues just makes them fall off the radar...
