### ISSUE TITLE
Can't get news for the second time

### ISSUE THREAD

**Issue by LouisHuangGT** [codelucas/newspaper#481]
If I run the same sample code that extracting CNN news for the second time, it will give me 0 articles. This happens on every site (can get some news for the first time running, but get nothing for the second time). What could be the reason of this problem?

**Comment by codelucas** [comment]
@dmilcevski thanks for answering. But this issue and others bring to light that the design may be flawed since it produces unexpected behavior :(

**Comment by JarbasAl** [comment]
bumping this, i think it makes more sense that  memoize_articles=False is a default, and that we may set it to True

i would also like a method to clear cache, so i can continue caching by efault but clear it on demand, during development this is annoying, specially if i want to demo to someone
