### ISSUE TITLE
Feature Request: Get location the article refers to.

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [codelucas/newspaper#507]
It would be nice to be able to get the location (like city names/places) that the article refers to.

**Comment by codelucas** [comment]
This is a tough problem that is out of the scope of this library. Reasoning is that what you are describing is a very tough NLP challenge. Though newspaper has some light NLP features it is mostly a smart HTML parsing library, such as: full-text extraction, title extraction, newsyness, top image extraction, etc.

Something like a text ==> location library can be standalone

**Comment by codelucas** [comment]
Thanks for bringing up this idea @ViRu-ThE-ViRuS 👍
