### ISSUE TITLE
New release? Newspaper version-0.2.6 issue tracker

### ISSUE THREAD

**Issue by PCManticore** [codelucas/newspaper#509]
Hey @codelucas I was wondering if there is a new release planned. The master seems to have some nice improvements.

**Comment by codelucas** [comment]
@PCManticore you asked just in time! 👍 😄 the new release has been pushed a few hours ago under version `0.2.6`, Please give it a run and let me know if you have any issues!

Until then we can leave this issue open.

**Comment by PCManticore** [comment]
Works like a charm @codelucas ! Thank you so much for the work!
