### ISSUE TITLE
how to use multithreading or multiprocessing with multiple article urls

### ISSUE THREAD

**Issue by rudvlf0413** [codelucas/newspaper#577]
I crawled some news portal sites and got some news article urls from that sites.

After that I want to crawl that news articles using newspaper library.

I think Article class in newspaper doesn't provide that function.
I don't know how to implement crawling codes that can use multithreading or multiprocessing with multiple article urls efficiently.

Is there any function or examples that I can use?

**Comment by jigarjit** [comment]
I did by using a array to store the url's and then running it through for loop to scrap the data and store in the format required.
Couldn't find the function for this as such.

**Comment by awiebe** [comment]
This might help
http://newspaper.readthedocs.io/en/latest/user_guide/advanced.html#multi-threading-article-downloads

**Comment by rudvlf0413** [comment]
@jigarjit Yeah I found this issue. I want newspaper merge this thread early :)

**Comment by terriblestoryteller** [comment]
@awiebe This doesn't work on article urls (`Article(url)`) , does it? Since `download_articles` isn't available on `Article` object but only available on `Source` object.

**Comment by codelucas** [comment]
Not sure if I understand your problem but can you try (recursively) using the `Source` functionality on that URL (via `newspaper.build('your url')` instead of the article object? `Article` objects are meant to abstract operations only related to a singular URL, like download html, parse full-text, get title, etc.
