### ISSUE TITLE
Gone for URL error

### ISSUE THREAD

**Issue by skrubber** [codelucas/newspaper#581]
Got this while trying to download:

Article `download()` failed with 410 Client Error: Gone for url: https://newsok.com/article/5596669/commercial-real-estate-transactions-from-the-oklahoman-for-june-2-2018 on URL https://newsok.com/article/5596669/commercial-real-estate-transactions-from-the-oklahoman-for-june-2-2018

Can you pls clarify what 'Gone for url' means? The url opens and has content btw - albeit has bullet points.

**Comment by awiebe** [comment]
HTTP 410: Gone
Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent.

**Comment by skrubber** [comment]
Sorry about that.
