### ISSUE TITLE
You must `download()` an article first!

### ISSUE THREAD

**Issue by Ask149** [codelucas/newspaper#594]
My code is getting the following error : ( This error does keep on repeating frequently with other links too even if the links are working fine )
You must `download()` an article first!
Error :  at url : https://www.wsj.com/articles/when-carter-page-met-stefan-halper-1527029988?mod=rss_opinion_main
You must `download()` an article first!
Error :  at url : https://www.wsj.com/articles/a-right-to-try-arrives-1527029964?mod=rss_opinion_main

Here's the code for downloading : 
def getArticle(blog):
    article = Article(blog.strip())
    article.download()
    article.parse()
    return article

**Comment by iwpnd** [comment]
```python
from newspaper import Article
url = 'https://www.wsj.com/articles/when-carter-page-met-stefan-halper-1527029988?mod=rss_opinion_main'

def getArticle(blog):
    article = Article(blog.strip())
    article.download()
    article.parse()
    return article

test = getArticle(url)
test.text
# >> 'Multiple media sources have now confirmed that American academic Stefan Halper is the “top secret” informant the FBI asked to sidle up to Trump campaign officials in 2016. Some questions follow: Who asked Mr. Halper to keep tabs on the Trump officials, and when and why?\n\nThe answers go to the credibility of the Federal Bureau of Investigation’s claim that it didn’t open an official counterintelligence probe into Trump-Russia collusion until July 31, 2016. The answers might also show if Obama Administration officials knew about...'
```

It works as intended for me.
The error you encounter is raised if you try to access the article before downloading and/or parsing it. Use my example and see if the error persists.

**Comment by estherelle** [comment]
So I actually got the same error as @Ask149 when I tried running this code. However, once I supplied the right proxy information, I was able to successfully run the code and get the output @iwpnd got.

```
from newspaper import Article
url = 'https://www.wsj.com/articles/when-carter-page-met-stefan-halper-1527029988?mod=rss_opinion_main'

# alternatively, allow getArticle to accept proxies as an argument
def getArticle(blog):
    # insert your proxies here
    proxies = {
                "http": "", 
                "https": ""
    }

    # pass proxies when creating Article object
    article = Article(blog.strip(), proxies=proxies)
    article.download()
    article.parse()
    return article

test = getArticle(url)
test.text
# >> 'Multiple media sources have now confirmed that American academic Stefan Halper is the “top secret” informant the FBI asked to sidle up to Trump campaign officials in 2016. Some questions follow: Who asked Mr. Halper to keep tabs on the Trump officials, and when and why?\n\nThe answers go to the credibility of the Federal Bureau of Investigation’s claim that it didn’t open an official counterintelligence probe into Trump-Russia collusion until July 31, 2016. The answers might also show if Obama Administration officials knew about...'
```

Hope this helps!

**Comment by Ask149** [comment]
Thanks a lot! the issue is resolved by using the following code.

def getArticle(blog):
    article = Article(blog.strip())
    article.download()

    while article.download_state != 2:
        time.sleep(1)

    article.parse()
    return article
