### ISSUE TITLE
Returns news object i need links 

### ISSUE THREAD

**Issue by priyanka22kar** [codelucas/newspaper#604]
import newspaper
article_urls = []
HTurl = newspaper.build("https://edition.cnn.com/")
for article in HTurl.articles:
    print(article)
    article_urls.append(article)

print(article_urls)

gives me this result:
<newspaper.article.Article object at 0x0000000003DF55C0>
I need the links 
instead of object

Please help thank you

**Comment by lis186** [comment]
Try the code snippet below.

```python
import newspaper

article_urls = []
HTurl = newspaper.build("https://edition.cnn.com/")
for article in HTurl.articles:
    print(article.url)
    article_urls.append(article.url)

print(article_urls)
```

**Comment by codelucas** [comment]
Thanks for giving the fix @lis186
