### ISSUE TITLE
Newspaper is scraping url's of the articles two times 

### ISSUE THREAD

**Issue by AbdulBsit** [codelucas/newspaper#606]
`import` newspaper

platform = newspaper.build("https://medium.com/topic/editors-picks", memoize_articles=False)
print(len(platform.articles))
articles = platform.articles
i=1
for article in articles:

    print("This is article ",i,article.url)
    i=i+1`
I scrapes the url of articles present in the page and got double urls

Article url 1 to 5 are same as article url 6 to 11 (see in the attachment)

![error](https://user-images.githubusercontent.com/32831612/43846681-8a98e25a-9b4c-11e8-8ee3-594eb5bdd7d9.png)

**Comment by ivanovishado** [comment]
Can you share the full code that you used for getting this result?
