### ISSUE TITLE
Please re-instate release creation

### ISSUE THREAD

**Issue by mckenzig** [codelucas/newspaper#649]
Hi when you release code to pypi, can you please create a numbered release in github? It would be great if the release in pypi could be tracked to a numbered release in git so that we can quickly check release notes.

Thanks.

**Comment by codelucas** [comment]
Got it, thanks for the heads up @mckenzig I will do so from now on

**Comment by linhy1993** [comment]
Hi @codelucas. Great project! 
Could you please keep github releases in sync with pypi. 
Thank you!
