### ISSUE TITLE
Is there a way to exclude portions of an article?

### ISSUE THREAD

**Issue by mzeidhassan** [codelucas/newspaper#656]
Hi all,

First, thanks for the great library. I am trying to extract the text from this [page](https://rising.globalvoices.org/blog/2018/03/06/the-mother-language-meme-challenge-2018-highlighted-the-internets-amazing-linguistic-diversity/) and it works fine, but it also extracts texts from tweets on that page. I also thought if I pass "language='en'", it should only extract English text, but this is not the case and it's extracting Asian text from that page for example.

My question is:
Is there a way to exclude portions of an article? Can I basically exclude tweets from that page?
Is there a way to pass a CSS selector for text exclusion or inclusion?

Thanks!

**Comment by therladbsgh** [comment]
You can use lxml to directly modify article.html, and remove parts of the HTML tree based on arbitrary attributes.

Here's an example for my current use case, which removes footers and navbars:

    from newspaper import Article
    import lxml.etree as etree

    ...

    article = Article(url)
    article.download()
    parser = etree.HTMLParser()
    tree = etree.parse(StringIO(article.html), parser)
    for elem in tree.iter('div'):
        if 'class' in elem.attrib and 'footer' in elem.attrib['class']:
            elem.getparent().remove(elem)
    for elem in tree.iter('nav'):
        elem.getparent().remove(elem)
    result = etree.tostring(tree.getroot(), method="html").decode("utf-8")
    article.html = result

**Comment by mzeidhassan** [comment]
Thanks @therladbsgh for your help. I appreciate it.
