### ISSUE TITLE
module initialization error [Errno 17] File exists: '/tmp/corpora'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [codelucas/newspaper#666]
Got this error today from my AWS Lambda. I see this error for the first time.

Version 0.2.8

**Comment by vitaly-zdanevich** [comment]
Thank you, but looks like now it resolved without my intervention (Lambda `Test` button), hm, strange why...

**Comment by Ask149** [comment]
> Thank you, but looks like now it resolved without my intervention (Lambda `Test` button), hm, strange why...

That's great then!
Could you please close this issue then?
Thanks.
