### ISSUE TITLE
util to forget cached for url

### ISSUE THREAD

**Issue by JarbasAl** [codelucas/newspaper#671]
as mentioned in https://github.com/codelucas/newspaper/issues/481

it would be nice to have a helper method to selectively clear cache for a certain website

i wanted to demo the cache functionality while using this, after i tested and before the demo i need to clear the cached articles

ideally this should work for a single source

quick and dirty solution
```python
def forget_articles(url):
    domain = \
        url.replace("https://", "http://").replace("http://", "").split("/")[0]
    d_pth = os.path.join(newspaper.settings.MEMO_DIR, domain + ".txt")
    if os.path.exists(d_pth):
        os.remove(d_pth)
```

**Comment by Interpause** [comment]
within newspaper.utils, there seems to be a function clear_memo_cache(source). Unfortunately it really seems the documentation is poorly made, apparently building the news source is supposed to reload the cached articles but it doesn't
