### ISSUE TITLE
issue with the new design at crhoy.com, it only reads 6 articles

### ISSUE THREAD

**Issue by Yuntaz** [codelucas/newspaper#680]
The newspaper portal has changed and today if we run the framework is only reading 6 articles. 

```
import newspapers
crhoy = newspaper.build('http://www.crhoy.com/', language='es')
print(len(crhoy.articles))
```

Do you see any workaround here?
Thanks

**Comment by Ennoriel** [comment]
Hi there,
You may use the "memoize_articles=False" config attribute. As stated in the doc : 

> "memoize_articles", default True, “cache and save articles run after run”

With this config, I get 55 articles which seems a bit low considering the home page of crhoy. Hops it hels you. :)

**Comment by Yuntaz** [comment]
Thanks you @Ennoriel
