### ISSUE TITLE
How can I download articles from a given url?

### ISSUE THREAD

**Issue by ChenjieXu** [codelucas/newspaper#682]
Is it possible to extract article urls from a certain page? build() method go lower level. I checked Source class. It seems that I can only extract articles by using category urls via categories_to_articles() method. My solution is
 `paper.categories = [Category(url = 'url_I_want')]  
paper.download_categories() 
paper.parse_categories() 
paper.generate_articles() `
But it seems too unprofessional. Is there official way to do this? Thank you in advance.

**Comment by Ennoriel** [comment]
Hello there,

Did you try using Source() instead of Article() ?

**Comment by Neileruaa** [comment]
Can I use Source() to find all articles for a category (for example : http://test.com/categoryExample) ?
