### ISSUE TITLE
newspaper download article in random order? 

### ISSUE THREAD

**Issue by jleung6** [codelucas/newspaper#689]

**Comment by jleung6** [comment]
when I tried to download articles from https://www.marketwatch.com/. The first article I got is apparently not from the big headlines on the front page, but somehow from an old article somewhere link to the navigation panel. Why this is happening? 

1 article: https://www.marketwatch.com/story/should-i-itemize-or-take-the-standard-tax-deduction-a-calculator-to-help-decide-2019-02-12

**Comment by codelucas** [comment]
There is no guarantee for order of url downloads, that logic is probably better suited for another service to perform after the downloading as finished.
