### ISSUE TITLE
[Errno 2] No such file or directory: '/tmp/.newspaper_scraper/article_resources'

### ISSUE THREAD

**Issue by dvtate** [codelucas/newspaper#715]
I'm running this on an AWS EC2 instance. Every time I attempt to scrape articles it's producing this error. I'm assuming this is a result of amazon deleting my `/tmp/` directory. If I restart the process everything works again, however doing so negatively impacts performance and uptime. 

**Is there a way to make newspaper use a different directory or to avoid caching to fs?**

**Comment by yaohongfenglove** [comment]
**Use the os.makedirs(resource_directory) method instead?**

**Comment by luguili-booker** [comment]
Hello, How was this problem solved? I encountered the same problem
