### ISSUE TITLE
Closing quotation mark is removed from title

### ISSUE THREAD

**Issue by igor-shevchenko** [codelucas/newspaper#73]
I work mostly with Russian articles. In Russian, «angled» quotes are main variation of quotation marks. So, I noticed that if there's «angled» quotes in a title of an article, all closing quotation marks are removed from extracted title and it contains only the opening ones. I found that in happens [here](https://github.com/codelucas/newspaper/blob/d6d16134d082f8d9e2b7b62c42265dbea73baa32/newspaper/extractors.py#L214) in `ContentExtractor`:

    TITLE_REPLACEMENTS = ReplaceSequence().create(u"&raquo;").append(u"»")
	
	...
	
	return TITLE_REPLACEMENTS.replaceAll(title).strip()
	
As far as I understand, it's needed for removing `»` from titles where this character is used as a delimiter. Maybe it'll make sense to modify the regular expressions to not remove right quotes that have left quotes before them?

[Here](http://vibirai.ru/articles/vyigray_bilety_na_oficialnuu_premeru_neuderjimye_3_v_kinomaks_ur-1201706)'s an example of a page that have broken quotation marks in extracted title (Russian language).

**Comment by codelucas** [comment]
I agree with you. But, let's see those PRs and make a decision from there when we can make tests.

**Comment by yprez** [comment]
I noticed that when "»" is used as a separator it's usually surrounded by spaces, but not when used as a quote. So changing the line to `ARROWS_SPLITTER = StringSplitter(" » ")` should probably fix this issue, while preserving the title parsing.

The `TITLE_REPLACEMENTS` does seem redundant, as it does the same thing as ARROWS_SPLITTER. I don't see the need for it there...
