### ISSUE TITLE
Article from HTML

### ISSUE THREAD

**Issue by ekaterinasmarp** [codelucas/newspaper#744]
Our use case is to transform the html to the plain text and save it in our system. The important point here is that there is no html resource with URL containing this HTML, html is just stored somewhere in our system. 
Is it possible to create and parse Article object without URL by setting the html directly to it?

**Comment by iwpnd** [comment]
from newspaper import fulltext

fulltext(html, language)

**Comment by ekaterinasmarp** [comment]
Thanks @iwpnd, you saved my day!
