### ISSUE TITLE
Differences beetween methods

### ISSUE THREAD

**Issue by rrafaelpinto** [codelucas/newspaper#748]
Hi, 

I'd like to know the differences between article.text and newspaper.fulltext(article.article_html)?

**Comment by iwpnd** [comment]
One is a variable, the other is a method.

You can either run an article through the whole build process (download, parse -> article.text), or you can use newspaper.fulltext() and only pass a html. Both use the same parsers/cleaners, just fulfill different use cases - afaik.

**Comment by rrafaelpinto** [comment]
Great, Tks
