### ISSUE TITLE
Does newspaper work with Google Colab?

### ISSUE THREAD

**Issue by nonoumasy** [codelucas/newspaper#769]
On Google Colab, when I try to extract an attribute like 'author', or 'publish_date' it will output an empty list or string. Is there an issue using Colab>?

sample code.
from newspaper import Article 
url = 'https://mystudentvoices.com/it-took-me-2-years-to-get-1000-followers-life-lessons-ive-learned-throughout-the-journey-9bc44f2959f0'
article = Article(url)
article.download()
article.publish_date

Output:
''

**Comment by Kerl1310** [comment]
You need to do `article.parse()` after `article.download()`

**Comment by nonoumasy** [comment]
thanks. that works!
