### ISSUE TITLE
Quote extraction from the news articles

### ISSUE THREAD

**Issue by thak123** [codelucas/newspaper#772]
Is there way to extract quotes from the news articles text using newspaper

**Comment by Kerl1310** [comment]
In what way? Do you mean as in extracting anything within speech/quotation marks? Only way I can think of doing this would be to do something like this...

```python
text = fulltext(html)
text.split('"')
```

...then taking every other result.

**Comment by thak123** [comment]
There are around 4-5 different quotation templates out there. and simple " split will solve 2 of the cases but not all.  Thanks for the reply
