### ISSUE TITLE
Unable to build Source object or newspaper from CNN/Bloomberg

### ISSUE THREAD

**Issue by ckl2007** [codelucas/newspaper#780]
Trying to extract from articles from a few different websites and have found that when I use CNN and Bloomberg that after building the size is 0. Have tried to use a Source level object as well and didn't get anything back.

**Comment by egodby** [comment]
Try to change the website name. For example, instead of `newspaper.build('http://cnn.com')`, try `newspaper.build('http://www.cnn.com')`.
