### ISSUE TITLE
ImportError: cannot import name 'Article' from 'newspaper'

### ISSUE THREAD

**Issue by jasch-shah** [codelucas/newspaper#782]
Installed using pip install newspaper3k command
It says requirement already satisfied.

(venv) C:\Users\x.y\Projects\Prod2>pip3 install newspaper3k
Requirement already satisfied: newspaper3k in c:\users\x.y\projects\prod2\venv\lib\site-packages (0.2.8)
Requirement already satisfied: nltk>=3.2.1 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (3.4.5)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (2.8.0)
Requirement already satisfied: requests>=2.10.0 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (2.22.0)
Requirement already satisfied: beautifulsoup4>=4.4.1 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (4.8.2)
Requirement already satisfied: Pillow>=3.3.0 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (7.0.0)
Requirement already satisfied: lxml>=3.6.0 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (4.5.0)
Requirement already satisfied: feedfinder2>=0.0.4 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: tinysegmenter==0.3 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (0.3)
Requirement already satisfied: feedparser>=5.2.1 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (5.2.1)
Requirement already satisfied: cssselect>=0.9.2 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (1.1.0)
Requirement already satisfied: PyYAML>=3.11 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (5.3)
Requirement already satisfied: jieba3k>=0.35.1 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: tldextract>=2.0.1 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from newspaper3k) (2.2.2)
Requirement already satisfied: six in c:\users\x.y\projects\prod2\venv\lib\site-packages (from nltk>=3.2.1->newspaper3k) (1.12.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from requests>=2.10.0->newspaper3k) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from requests>=2.10.0->newspaper3k) (1.25.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from requests>=2.10.0->newspaper3k) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from requests>=2.10.0->newspaper3k) (2.8)
Requirement already satisfied: soupsieve>=1.2 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (1.9.5)
Requirement already satisfied: setuptools in c:\users\x.y\projects\prod2\venv\lib\site-packages\setuptools-40.8.0-py3.7.egg (from tldextract>=2.0.1->newspaper3k) (40.8.0)
Requirement already satisfied: requests-file>=1.4 in c:\users\x.y\projects\prod2\venv\lib\site-packages (from tldextract>=2.0.1->newspaper3k) (1.4.3)

(venv) C:\Users\X.Y\Projects\Prod2>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from newspaper import Article
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\X.Y\Projects\Prod2\newspaper.py", line 1, in <module>
    from newspaper import Article
ImportError: cannot import name 'Article' from 'newspaper' (C:\Users\X.Y\Projects\Prod2\newspaper.py)
>>> exit()

What should I do ?

**Comment by iwpnd** [comment]
looks like you have a `newspaper.py` file in your project directory that interferes with the import of newspaper.

**Comment by jasch-shah** [comment]
Thanks @iwpnd
