### ISSUE TITLE
Option to remove certain tags

### ISSUE THREAD

**Issue by sai-krishna-msk** [codelucas/newspaper#806]
is there an option to eliminate contents of certain tags from downloaded HTML articles?

For example, 
I don't want to include content present in between the tags (<qazx></qazx>) 

Thank you

**Comment by innovative-roh** [comment]
It would be really great if we could do add custom tags which we don't want to extract . @sai-krishna-msk  There's no documentation regarding  this feature so most probably this is not possible for now i guess.
