### ISSUE TITLE
Travis ci test pdf download

### ISSUE THREAD

**Issue by Bachstelze** [codelucas/newspaper#820]
The current build fails with:
```
FAIL: test_article_pdf_ignoring (__main__.TestDownloadPdf)
----------------------------------------------------------------------

Traceback (most recent call last):

  File "tests/unit_tests.py", line 42, in run

    method(*args, **kw)

  File "tests/unit_tests.py", line 763, in test_article_pdf_ignoring

    self.assertEqual(empty_pdf, a.html)

AssertionError: '%PDF-' != ''

- %PDF-

+
```

This could be due to a wrong url in the unit test, which could be fixed in https://github.com/codelucas/newspaper/pull/819
The travis pipeline passed with this fix: https://travis-ci.org/github/codelucas/newspaper/builds/701978559

**Comment by codelucas** [comment]
Sounds good, let me merge that one in. Good find (y)

**Comment by codelucas** [comment]
merge
