### ISSUE TITLE
Zero articles being downloaded from CNN.com

### ISSUE THREAD

**Issue by thomsonian2023** [codelucas/newspaper#821]
I am using the following code:
```
import newspaper
    cnn_paper = newspaper.build('https://www.cnn.com/', language='en')
    for article in cnn_paper.articles:
        print(article.url)
```
It prints 0 articles
but when I leave out the language='en', it prints lot of spanish URLs.

**Comment by AndreaRe9** [comment]
Have you tried to see if news articles are already in cache? 
If you are on linux, there should be a hidden folder at /tmp/.newspaper_scraper/memoized that contains files with articles scraped from different sources. If you have run the same code previously, the news articles are saved in cache and they won't be printed.

**Comment by santoshbs** [comment]
This should work:
cnn_paper = newspaper.build('http://cnn.com', memoize_articles=False)
