### ISSUE TITLE
Unable to get all articles from a news site

### ISSUE THREAD

**Issue by adastra21** [codelucas/newspaper#823]
I'm interested in scraping all news articles from the past 5 years from different news sites. Is that possible through newspaper? As an example, the maximum that I seem to get from Breitbart is about 754 (going back approx. a month).

```
paper = newspaper.build("https://www.breitbart.com", memoize_articles=False)
paper.size()
>> 754
```

**Comment by lukaspistelak** [comment]
try to use scrapy spider
