### ISSUE TITLE
Is there a list of supported sites?

### ISSUE THREAD

**Issue by jtara1** [codelucas/newspaper#840]
Which domains or webpages can be scraped?

**Comment by johnbumgarner** [comment]
from the code -- these items cannot be scraped. 

BAD_CHUNKS = ['careers', 'contact', 'about', 'faq', 'terms', 'privacy',
              'advert', 'preferences', 'feedback', 'info', 'browse', 'howto',
              'account', 'subscribe', 'donate', 'shop', 'admin']

BAD_DOMAINS = ['amazon', 'doubleclick', 'twitter']

**Comment by jtara1** [comment]
I'm surprised to see I haven't found a news site that this can't scrape. It's met my needs anyways.

**Comment by johnbumgarner** [comment]
Yes, Newspaper has a lot of flexibility.  I recently started putting together a detailed Newspaper3k usage document that I publicly share. The document is available here: https://github.com/johnbumgarner/newspaper3_usage_overview. Please let me know if you see anything that is missing or needs more clarification.

**Comment by ahadafzal** [comment]
u can't scrape javascript rendered pages

**Comment by johnbumgarner** [comment]
> u can't scrape javascript rendered pages

What javascript rendered site are you trying to scrape?
