### ISSUE TITLE
Add support for zeit.de

### ISSUE THREAD

**Issue by m-rey** [codelucas/newspaper#841]
It would be great to also support https://zeit.de.
Currently, it appears to be unsupported.

How can devs add support for more websites?

**Comment by johnbumgarner** [comment]
I'm been using Newspaper3k and following the issues raised about this library.  When I queried https://zeit.de using Newspaper I received this 'Lesen Sie zeit.de mit Werbung oder im PUR-Abo. Sie haben die Wahl.'  I'm unsure, why Newspaper3k cannot access this site. I was able to access this site using Python Requests and Newspaper3k.  

I recently started putting together a detail Newspaper3k usage document that I publicly sharing.  This document is available here: https://github.com/johnbumgarner/newspaper3_usage_overview.  It contains the extraction code for https://zeit.de.  

P.S. this document is a work in process, so more information will be added.

**Comment by JulianWgs** [comment]
It asks whether to browse Zeit.de with ads and tracking or pay for the subscription. You can see this for yourself by visiting the site after you cleared all cookies. Many other sites switched to this banner in recent months. Unfortunately I couldn't get around this by saving the session cookie [with this method](https://stackoverflow.com/a/61750071/8500357). The code in your repository doesn't work for me.

**Comment by johnbumgarner** [comment]
@JulianWgs I'm not sure what changed on the site in the last 27 days, because now the example doesn't work.  I need to revisit the code and the site to determine how to fix this.  Thanks for pointing out this breakage.

**Comment by johnbumgarner** [comment]
> It asks whether to browse Zeit.de with ads and tracking or pay for the subscription. You can see this for yourself by visiting the site after you cleared all cookies. Many other sites switched to this banner in recent months. Unfortunately I couldn't get around this by saving the session cookie [with this method](https://stackoverflow.com/a/61750071/8500357). The code in your repository doesn't work for me.

I looked into this issue. _Newspaper_ cannot extract any content from the site until you add additional code that bypasses the tracking/ad button.  Once you do that _Newspaper_ should operate correctly.

**Comment by mircealungu** [comment]
any progress on this issue? many other german sites seem to be in the same situation.

**Comment by johnbumgarner** [comment]
> any progress on this issue? many other german sites seem to be in the same situation.

I didn't write any code for Zeit.de to specifically bypass the add acknowledgement button.  I did write some code to bypass an acknowledgement button on Al Arabiya.  That code provides you a basic framework to bypass the button on Zeit.de.  The code is in this document:  https://github.com/johnbumgarner/newspaper3_usage_overview. 

If you have any issues please reach out and I will help you.

**Comment by johnbumgarner** [comment]
> any progress on this issue? many other german sites seem to be in the same situation.

I wrote some code to handle the GDPR acknowledgement on most German language news sites.  I didn't write the code to scrape the articles, because I don't speak German and don't know what is important.  I did add the code to start the article scraping, which needs to be enhanced by the end user of the code.  I will post the code tomorrow to my overview document.

**Comment by johnbumgarner** [comment]
> It would be great to also support https://zeit.de.
> Currently, it appears to be unsupported.
> 
> How can devs add support for more websites?

@m-rey This issue has been resolved.  Please close this issue.

**Comment by JulianWgs** [comment]
I‘m getting 404 error from GitHub

**Comment by m-rey** [comment]
Fixed in https://github.com/johnbumgarner/newspaper3_usage_overview/commit/b20ff72b4e2397239cb61ad0f71e81fa26a89472

**Comment by johnbumgarner** [comment]
> I‘m getting 404 error from GitHub

Which GitHub Repository?

**Comment by JulianWgs** [comment]
> The code is located under - News sites with a GDPR acknowledgement button - in my overview document

The link you posted. A dot slipped into it. Without it, it works fine.

https://github.com/johnbumgarner/newspaper3_usage_overview

Thank you!
