### ISSUE TITLE
Newsletter appears to fail to extract body from very simple html page

### ISSUE THREAD

**Issue by boxabirds** [codelucas/newspaper#858]
Problem: extract content from [this page](https://lisn-tests.netlify.app/simplest.html)

Expected result: 

```
newspaper.html =
<html>
  <head>
    <title>Test title</title>
  </head>
  <body>
    <p>Simplest.</p>
  </body>
</html>
```

`newspaper.text = "Simplest."`

Observed:
`newspaper.html` is correct, but `newspaper.text` is blank.

**Comment by johnbumgarner** [comment]
_Newspaper_ has minimum length requirements for extracting  an _article.text_ . 

reference from the code: 

     def is_valid_body(self):
        """If the article's body text is long enough to meet
        standard article requirements, keep the article
        """

**Comment by boxabirds** [comment]
Thanks. So working as intended I guess. Fair enough given how much noise there is on small pages.
