### ISSUE TITLE
Newspaper not extracting pages for Fox Baltimore

### ISSUE THREAD

**Issue by srik506** [codelucas/newspaper#859]
I was trying to test it on a few webpages where it worked as expected but when i tried https://www.foxbaltimore.com, it doesn't extract anything. Could it be because of user agent?

import newspaper
url='https://www.foxbaltimore.com'
fox = newspaper.build(url, memoize=False)
fox.size()

The above returns 0.
I tried to check whether the articles are already generated but nothing in the memoize directory.

**Comment by johnbumgarner** [comment]
Please take a look at the extraction code for Fox in this [overview document ](https://github.com/johnbumgarner/newspaper3_usage_overview)that I wrote on using Newspaper.  Please let me know if the extraction code in the overview doesn't work for you.

**Comment by srik506** [comment]
> Please take a look at the extraction code for Fox in this [overview document ](https://github.com/johnbumgarner/newspaper3_usage_overview)that I wrote on using Newspaper. Please let me know if the extraction code in the document doesn't work for you.

Thanks for the information. I have tried it with multiple user agents but though its working for a specific article, when I am using it for building articles, it doesn't seem to work.
i.e. _fox = newspaper.build(url, config)
fox.size()
0_

**Comment by johnbumgarner** [comment]
I looked into this issue.  The navigational structure of _foxbaltimore.com_ cannot be parsed using either _newspaper.build_ or _newspaper.source_. You will need to use _from newspaper.utils import BeautifulSoup_ with _newspaper.article_ to parse the site.  Look at the page source to see the structural issue.

**Comment by johnbumgarner** [comment]
Please look at the extraction example in my overview document that I wrote for foxbaltimore.com.  This example required a lot of JSON extraction, which Newspaper is not designed to do. You should be able to modify any of the examples within my document to extract content from most news sources.  Good luck with your web scraping.

**Comment by srik506** [comment]
Thanks @johnbumgarner!!

**Comment by johnbumgarner** [comment]
> Thanks @johnbumgarner!!

You're welcome.  I'm glad that I could help you solve this issue.  Please do me a favorite and close this open issue.
