### ISSUE TITLE
bypass GDPR Cookie agreement

### ISSUE THREAD

**Issue by draganov12** [codelucas/newspaper#879]
Hi!
Im both new to coding and this is my first post on GitHub (pls be kind with me :) )..

I'm scraping an article from a specific site and unfortunatly i cant bypass the gdpr cookie agreement. Insead of the script downloading the main article, I only succeed in downloading the text for the gdpr agreement, as seen below.

Any ideas on how i can bypass this?

Thanx!!
![bypass](https://user-images.githubusercontent.com/82116974/113918839-2dff2b80-97e3-11eb-9953-9c27b9e44797.png)

**Comment by johnbumgarner** [comment]
Yes. Take a look at the example in my [newspaper3 usage overview document.](https://github.com/johnbumgarner/newspaper3_usage_overview) You will have to modify the example to fit your use case. 

P.S. Please close this issue, if my overview document helps you solve this problem.

**Comment by draganov12** [comment]
I will try this definitely! Thnx for the assistance.
