### ISSUE TITLE
Add custom cookies

### ISSUE THREAD

**Issue by moll-re** [codelucas/newspaper#888]
This module is amazing, I love it. I was just wondering, if it might be possible to specify custom cookies in order to bypass paywalls and obstacles of the likes. I imagine these would have to be specified alongside the user agent but I couldn't find any mention of this. Has anyone tried this yet or could point me towards resources to do this? Thanks!

**Comment by johnbumgarner** [comment]
Under the hood Newspaper uses _Python Requests_, so you can pass cookie info in the headers.  

Reference my [Newspaper3 Usage Overview document](https://github.com/johnbumgarner/newspaper3_usage_overview) for details on how to use _headers_.

Let me know if you need any additional assistance. If not, please close this issue. Thanks.
