### ISSUE TITLE
getting newspaper.article.ArticleException for the urls given from forbes website

### ISSUE THREAD

**Issue by Swarnitha-eluru** [codelucas/newspaper#889]
I am getting this issue only for the urls given from forbes website.
My code was :
                        Input_url="https://www.forbes.com/sites/ajherrington/2021/04/23/steve-deangelo-has-a-vision-for-global-cannabis-legalization/"
                        resp = requests.get(Input_url)            
			result=newspaper.fulltext(resp.text)      
			user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
			
			config = Config()
			config.browser_user_agent = user_agent
			article = Article(Input_url, keep_article_html=True,config=config)
			article.download()                      
			article.parse()                           
			article.nlp()         

The same code is working in my local system for any kinds of urls from any website,but the same code got deployed in docker container when given urls from forbes website I am facing issue like 
**newspaper.article.ArticleException
newspaper.article.ArticleException: Article `download()` failed with 403 Client Error: Max restarts limit reached for url: https://www.forbes.com/sites/ajherrington/2021/04/23/steve-deangelo-has-a-vision-for-global-cannabis-legalization/ on URL https://www.forbes.com/sites/ajherrington/2021/04/23/steve-deangelo-has-a-vision-for-global-cannabis-legalization/.**

Can I know why this is happening ? Is there any change to be made in user-agent assignment?
please give me a solution for my issue.

**Comment by johnbumgarner** [comment]
First, this issue isn't related to Newspaper.

Second, a _403 Client Error_ means that accessing a URL or resource is absolutely forbidden by the provider of that content.  I would speculate that you were blocked by Forbes, because you have reached your 4 free article limited.  I know that Forbes tracks you by IP address. 

There are two ways to bypass the 403 Client Error: 

1.  Obtain a paid subscription to Forbes.com 
2.  Use a proxy 

Let me know if you need any additional assistance.   If not, please close this issue.  Thanks.

P.S. I have information on how to use a proxy in my [overview document on Newspaper](https://github.com/johnbumgarner/newspaper3_usage_overview)

**Comment by Swarnitha-eluru** [comment]
Thanks a lot for your support .

**Comment by Swarnitha-eluru** [comment]
I included those proxy lines in my code but am not able to get response for any articles in my local pc .
And If I didn't include the proxy lines am able to get the response for Forbes also in my local pc for any number of times.
Forbes articles are restricting the limit only for the same code deployed in docker. I am facing only for docker set up code not for the code in my pc.
Can I know what's the difference between them?

**Comment by johnbumgarner** [comment]
What proxy service are you using?

**Comment by johnbumgarner** [comment]
Which proxy service are you using?  


> I included those proxy lines in my code but am not able to get response for any articles in my local pc .
> And If I didn't include the proxy lines am able to get the response for Forbes also in my local pc for any number of times.
> Forbes articles are restricting the limit only for the same code deployed in docker. I am facing only for docker set up code not for the code in my pc.
> Can I know what's the difference between them?

**Comment by Swarnitha-eluru** [comment]
user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
PROXIES = {
           'http': "http://127.0.0.1:3300",
           'https': "https://127.0.0.1:3300"
          }


config = Config()
config.browser_user_agent = user_agent
config.proxies = PROXIES
article = Article(Input_url, keep_article_html=True,config=config)
article.download()                      
article.parse()                           
article.nlp()

**Comment by johnbumgarner** [comment]
What proxy service are you using?

**Comment by Swarnitha-eluru** [comment]
default proxy settings.And one more thing before I add the proxy lines I worked with the previous code it got worked for forbes 10000 urls in my local pc.I am facing the issue in docker aws ec2 instance

**Comment by johnbumgarner** [comment]
So you have a local lists of 10,000 Forbes articles that you passed to Article(Input_url, keep_article_html=True,config=config)?

**Comment by Swarnitha-eluru** [comment]
yes I gave one forbes url and ran for 10000 times in my local machine

**Comment by johnbumgarner** [comment]
Again this issue isn't related to Newspaper.   I just requested 10 different articles from Forbes and received a status code of 200 for my _Python Request_s.  I ran the same query through Newspaper, which produced no errors.  I also tried using a HTTPS proxy with both _Python Requests_ and _Newspaper_.  Both of the proxy tests also produced no errors.

**Comment by Swarnitha-eluru** [comment]
can u share your  code

**Comment by johnbumgarner** [comment]
> can u share your code

I used the Newspaper code from my overview document.   I have also written various examples within these:

https://stackoverflow.com/questions/tagged/newspaper3k

https://stackoverflow.com/questions/tagged/python-newspaper

**Comment by Swarnitha-eluru** [comment]
okay thank you
