### ISSUE TITLE
How to save the text file of a news link with file name as title of the article?

### ISSUE THREAD

**Issue by githubtrip** [codelucas/newspaper#908]
How to save the text file of a news link with file name as title of the article?
eg. I want to save the content of this news page in a text file with the file name as "title of the article.txt"
https://www.msn.com/en-us/news/us/passenger-accused-of-punching-southwest-flight-attendant-faces-federal-charges/ar-AAO4AFu?ocid=entnewsntp

**Comment by johnbumgarner** [comment]
What do you consider the content of this news page?

**Comment by githubtrip** [comment]
Nevermind. Solved. Thanks

**Comment by Aliktk** [comment]
@githubtrip  How you did it?
