### ISSUE TITLE
Newspaper unable to retrieve any articles from headlinesoftoday.com

### ISSUE THREAD

**Issue by jack-fireworkhq** [codelucas/newspaper#912]
![image](https://user-images.githubusercontent.com/80802145/135191802-ecf377ce-64e7-4a95-b770-c82987eca214.png)

https://www.headlinesoftoday.com
It seems like not working on this URL.

**Comment by johnbumgarner** [comment]
I just tested that site in question and it works correctly with _newspaper._  Please reference my [Newspaper Overview document](https://github.com/johnbumgarner/newspaper3_usage_overview) for the correct way to use Build.

**Comment by jack-fireworkhq** [comment]
Thank you, I already made it work, thanks for your help.

**Comment by johnbumgarner** [comment]
You're welcome.
