### ISSUE TITLE
is the newspaper.build fuction still work? since it never print out anything. 

### ISSUE THREAD

**Issue by mobilelifeful** [codelucas/newspaper#926]
Trying to play around with it, but it doesn't print out anything.
>>> import newspaper
>>> cnn_paper = newspaper.build('http://cnn.com')
>>> for article in cnn_paper.articles:
>>>     print(article.url)

**Comment by johnbumgarner** [comment]
Please review the Source.build() examples in my [newspaper3 usage overview document](https://github.com/johnbumgarner/newspaper3_usage_overview).

Also what is your use case for scraping all the articles on CNN.com?  

P.S. Please close this issue, if my overview document helps you solve this problem.
