### ISSUE TITLE
It can't work with BBC

### ISSUE THREAD

**Issue by Qggg** [codelucas/newspaper#939]
I try it with BBC, for example :https://www.bbc.com/news/world-europe-61204543

it can't fetch Authors ,and can't fetch the full text.

something went wrong.

**Comment by johnbumgarner** [comment]
Take a look at this [document](https://github.com/johnbumgarner/newspaper3_usage_overview) that I wrote on using newspaper3k.  It has details on extracting content from BBC.  Let me know if my extraction guidelines work for you.

**Comment by Qggg** [comment]
> Take a look at this [document](https://github.com/johnbumgarner/newspaper3_usage_overview) that I wrote on using newspaper3k. It has details on extracting content from BBC. Let me know if my extraction guidelines work for you.

Yes,it works. You pick the elements from script segment, in this way, you can also pick the 'article content  text' in 'script nonce' seg. It seems like there are no easy and clear way to work with BBC.

Thank you.

it can be closed.
