### ISSUE TITLE
jpeg error with PIL, Can't convert 'NoneType' object to str implicitly

### ISSUE THREAD

**Issue by hnykda** [codelucas/newspaper#95]
Hello, 

when I try for example this code:

```
url = "http://www.huffingtonpost.com/2014/12/16/politifact-lie-of-the-year-ebola_n_6335360.html"
a = nws.Article(url)
a.download()
a.parse()
```

I get this error:

```
CRITICAL:newspaper.article:jpeg error with PIL, Can't convert 'NoneType' object to str implicitly
```

everything works (I think) fine - at least I haven't found anything weird. I can give you additional info - not sure if that is bug or it's because of my configuration.

**Comment by jordimarinvalle** [comment]
Using python 2.7.8..

``CRITICAL:newspaper.article:jpeg error with PIL, cannot concatenate 'str' and 'NoneType' objects``

**Comment by jwarzech** [comment]
I see this error quite often as well.

**Comment by tgoodyear** [comment]
Same issue here.

**Comment by andessen** [comment]
Did anyone ever find a solution to this?

**Comment by vetal4444** [comment]
Try to install libjpeg-dev (on debian based distro) and reinstall pillow. That was helpful for me.

**Comment by codelucas** [comment]
Closing as this is fixed!
