### ISSUE TITLE
Parsing Problem

### ISSUE THREAD

**Issue by skittoo** [codelucas/newspaper#971]
for this link: https://www.cnn.com/2023/06/24/us/how-much-lake-mead-water-rise-climate/index.html
no parsing output!

**Comment by johnbumgarner** [comment]
Can you provide your code?

**Comment by skittoo** [comment]
from newspaper import Article

url = 'https://www.cnn.com/2023/06/24/us/how-much-lake-mead-water-rise-climate/index.html'

article = Article(url)

article.download()

article.parse()

print(article.authors)

print(article.publish_date)

print(article.text)

print(article.top_image)

**Comment by skittoo** [comment]
> Can you provide your code?

from newspaper import Article

url = 'https://www.cnn.com/2023/06/24/us/how-much-lake-mead-water-rise-climate/index.html'

article = Article(url)

article.download()

article.parse()

print(article.authors)

print(article.publish_date)

print(article.text)

print(article.top_image)

**Comment by johnbumgarner** [comment]
Thanks for sharing your code.  Please take a look at the CNN extraction example in my repository on [newspaper3 usage](https://github.com/johnbumgarner/newspaper3_usage_overview).  I tested my example code with your URL and it works.  If you have any additional questions about newspaper3 usage please open an issue in my repository and I will see what I can do to help.

**Comment by skittoo** [comment]
Thank you 

> Thanks for sharing your code. Please take a look at the CNN extraction example in my repository on [newspaper3 usage](https://github.com/johnbumgarner/newspaper3_usage_overview). I tested my example code with your URL and it works. If you have any additional questions about newspaper3 usage please open an issue in my repository and I will see what I can do to help.

Thanks ! This was really helpful <3

**Comment by johnbumgarner** [comment]
You're welcome.  Plus star my repository as part of GitHub's gamification process.  ;-} 

Also remember to close this issue on this repository.

**Comment by skittoo** [comment]
Sure
